import { useCallback } from 'react';
import { useI18n, type Language } from '../i18n/I18nProvider';

const de = {
  'shared.scope': 'Ligaleitung · {league}',
  'shared.deniedTitle': 'Zugriff verweigert',
  'shared.back': 'Zur Ligaleitung',
  'shared.retry': 'Erneut versuchen',
  'shared.close': 'Schließen',
  'shared.save': 'Speichern',
  'shared.saving': 'Speichern …',
  'shared.edit': 'Bearbeiten',
  'shared.action': 'Aktion',
  'shared.status': 'Status',
  'shared.active': 'Aktiv',
  'shared.inactive': 'Inaktiv',
  'drivers.denied': 'Du benötigst die Rolle Ligaleitung, um Fahrer zu verwalten.',
  'drivers.loading': 'Starterfeld und Fahrerzuordnungen werden geladen.',
  'drivers.loadingTitle': 'Fahrer werden geladen',
  'drivers.loadError': 'Fahrer konnten nicht geladen werden.',
  'drivers.loadErrorTitle': 'Fahrer konnten nicht geladen werden',
  'drivers.created': 'Fahrer wurde angelegt.',
  'drivers.updated': 'Fahrer wurde aktualisiert.',
  'drivers.saveError': 'Fahrer konnte nicht gespeichert werden.',
  'drivers.title': 'Fahrer verwalten',
  'drivers.copy': 'Startnummern, Teams, Fahrzeuge und aktive Fahrer der ausgewählten Liga pflegen. Bestehende Ergebnisse werden beim Bearbeiten nicht verändert.',
  'drivers.create': 'Fahrer anlegen',
  'drivers.edit': 'Fahrer bearbeiten',
  'drivers.new': 'Neuer Fahrer',
  'drivers.displayName': 'Anzeigename',
  'drivers.gamertag': 'Gamertag',
  'drivers.number': 'Startnummer',
  'drivers.nationality': 'Nationalität',
  'drivers.team': 'Team',
  'drivers.car': 'Fahrzeug',
  'drivers.active': 'Aktiver Fahrer',
  'drivers.activeHint': 'In Auswahlfeldern und aktuellen Übersichten anzeigen.',
  'drivers.save': 'Fahrer speichern',
  'drivers.total': 'Fahrer gesamt',
  'drivers.linked': 'Mit Konto verknüpft',
  'drivers.grid': 'Starterfeld',
  'drivers.list': 'Fahrer',
  'drivers.teamCar': 'Team / Fahrzeug',
  'drivers.results': 'Ergebnisse',
  'drivers.accountLinked': 'Konto verknüpft',
  'drivers.noAccount': 'Kein Konto verknüpft',
  'drivers.noCar': 'Kein Fahrzeug',
  'drivers.emptyTitle': 'Noch keine Fahrer',
  'drivers.emptyCopy': 'Lege den ersten Fahrer an, um ein Starterfeld aufzubauen.',
  'import.denied': 'Du benötigst die Rolle Ligaleitung, um Ergebnisse zu importieren und freizugeben.',
  'import.loading': 'Rennen, Fahrer und bestehende Entwürfe werden für die Prüfung vorbereitet.',
  'import.loadingTitle': 'Ergebnisimport wird geladen',
  'import.workspaceLoadError': 'Import konnte nicht geladen werden.',
  'import.workspaceLoadErrorTitle': 'Ergebnisimport konnte nicht geladen werden',
  'import.selectRaceError': 'Bitte zuerst das passende Rennen auswählen.',
  'import.preparing': 'Bilder werden vorbereitet (0/{count}) …',
  'import.prepared': 'Bild {completed} von {total} vorbereitet: {file}',
  'import.uploading': 'Bilder werden sicher an die KI übertragen …',
  'import.analysisDone': 'KI-Analyse abgeschlossen: {count} Ergebniszeilen erkannt. Bitte die Tabelle kontrollieren und die Punkte bestätigen.',
  'import.draftSaved': 'Ergebnisentwurf wurde geprüft und gespeichert. Offizielle Daten sind noch unverändert.',
  'import.published': 'Ergebnisversion wurde offiziell veröffentlicht.',
  'import.publishError': 'Ergebnis konnte nicht veröffentlicht werden.',
  'import.analysisError': 'KI-Bilder konnten nicht ausgewertet werden.',
  'import.draftError': 'Entwurf konnte nicht erstellt werden.',
  'import.title': 'Ergebnisimport & Freigabe',
  'import.copy': 'Ergebnisbilder per KI oder eine CSV einlesen, übersichtlich prüfen und zuerst als revisionssicheren Entwurf speichern.',
  'import.selectRace': '1. Rennen auswählen',
  'import.chooseRace': 'Rennen wählen',
  'import.reasonImages': 'Ergebnisimport per KI-Bildanalyse',
  'import.reasonCsv': 'Ergebnisimport per CSV',
  'import.reason': '2. Änderungsgrund',
  'import.reasonPlaceholder': 'z. B. Ergebnisbilder vom Rennabend',
  'import.method': 'Importmethode',
  'import.images': 'Bilder mit KI',
  'import.imagesHint': 'Empfohlen für Screenshots aus dem Spiel',
  'import.csv': 'CSV-Datei',
  'import.csvHint': 'Für vorbereitete Ergebnistabellen',
  'import.selectImages': 'Ergebnisbilder auswählen',
  'import.imagesCopy': 'Bis zu 8 Screenshots werden verkleinert übertragen und automatisch ausgelesen.',
  'import.imageLabel': 'Ergebnisbilder',
  'import.imageSelected.one': '1 Bild ausgewählt · {files}',
  'import.imageSelected.other': '{count} Bilder ausgewählt · {files}',
  'import.imageFormats': 'JPG, PNG, WebP, HEIC oder HEIF · maximal 20 MB pro Bild',
  'import.analyze': 'Bilder auslesen',
  'import.analyzing': 'Import läuft …',
  'import.selectCsv': 'CSV-Datei auswählen',
  'import.csvCopy': 'Lade eine vorbereitete Ergebnistabelle hoch und prüfe sie vor dem Speichern.',
  'import.csvColumns': 'Fahrer, Position, Grid, Punkte, Team sowie optional Stopps und Zeiten',
  'import.csvReadError': 'CSV-Datei konnte nicht gelesen werden.',
  'import.checkCsv': 'CSV-Daten prüfen',
  'import.checkCsvHint': 'Passe die importierten Werte bei Bedarf direkt hier an.',
  'import.waitingTitle': 'Noch keine Ergebnisse erkannt',
  'import.waitingCopy': 'Wähle oben die Ergebnisbilder aus und starte die Auswertung. Danach erscheint hier die bearbeitbare Tabelle.',
  'import.saveDraft': 'Entwurf speichern',
  'import.officialUnchanged': 'Die offiziellen Ergebnisse bleiben bis zur separaten Freigabe unverändert.',
  'import.release': 'Freigabe',
  'import.reviewedDrafts': 'Geprüfte Entwürfe',
  'import.rows': '{count} Ergebniszeilen · {status}',
  'import.publishNow': 'Jetzt offiziell freigeben',
  'import.noDraftsTitle': 'Keine offenen Entwürfe',
  'import.noDraftsCopy': 'Alle geprüften Ergebnisversionen sind verarbeitet. Neue Entwürfe erscheinen nach dem Speichern hier.',
  'import.aiWarnings': 'Hinweise der KI',
  'review.title': 'Erkannte Renndaten prüfen',
  'review.copy': 'Alle Felder lassen sich direkt bearbeiten. Fahrer und Punkte müssen vor dem Speichern bestätigt sein.',
  'review.rows': '{count} Zeilen',
  'review.mobileHint': 'Tippe auf einen Fahrer, um Zuordnung, Positionen, Zeiten und Punkte zu bearbeiten.',
  'review.position': 'Pos.',
  'review.driver': 'Fahrer',
  'review.match': 'Match',
  'review.team': 'Team',
  'review.grid': 'Grid',
  'review.stops': 'Stopps',
  'review.fastestLap': 'Beste Runde',
  'review.timeStatus': 'Zeit / Status',
  'review.points': 'Punkte',
  'review.assignDriver': 'Fahrer zuordnen',
  'review.leagueDriver': 'Ligafahrer',
  'review.finishPosition': 'Zielposition',
  'review.startPosition': 'Startposition',
  'review.fastestLapFull': 'Schnellste Runde',
  'review.raceTimeStatus': 'Rennzeit oder Status',
  'review.check': 'Prüfen',
  'review.assignmentMissing': 'Fahrerzuordnung fehlt',
  'review.pointsMissing': 'Punkte fehlen',
  'review.pointsShort': '{points} Pkt.',
  'review.tableLabel': 'Bearbeitbare erkannte Rennergebnisse',
  'review.mobileRowLabel': '{field} Mobil Zeile {row}',
  'review.rowLabel': '{field} Zeile {row}',
  'review.detected': 'Erkannt: {driver}',
  'review.confidence': '{confidence}% Matchsicherheit · {source}',
  'review.manual': 'Manuell gewählt',
  'review.unassigned': 'Nicht zugeordnet',
  'review.similar': 'Ähnlicher Name',
  'review.gamertag': 'Gamertag',
  'review.driverName': 'Fahrername',
  'review.inactive': 'inaktiv',
  'review.integerError': '{field} muss eine ganze Zahl ab {minimum} sein.',
  'review.emptyError': 'Die Prüftabelle enthält keine Ergebniszeilen.',
  'review.assignAllError': 'Bitte alle erkannten Fahrer einem Ligafahrer zuordnen.',
  'review.duplicateDriverError': 'Ein Fahrer darf pro Rennen nur einmal vorkommen.',
  'review.duplicateFinishError': 'Eine Zielposition darf nur einmal vergeben werden.',
  'review.driverUnavailableError': 'Der Fahrer in Zeile {row} ist nicht mehr verfügbar.',
  'review.pointsError': 'Bitte die Punkte in Zeile {row} prüfen.',
  'review.fastestLapError': 'Die schnellste Runde in Zeile {row} ist ungültig.',
} as const;

export type OperationsCopyKey = keyof typeof de;
type Values = Record<string, string | number>;
export type OperationsCopy = (key: OperationsCopyKey, values?: Values) => string;

const en: Record<OperationsCopyKey, string> = {
  ...de,
  'import.reasonImages': 'Result import via AI image analysis',
  'import.reasonCsv': 'Result import via CSV',
  'shared.scope': 'League management · {league}', 'shared.deniedTitle': 'Access denied', 'shared.back': 'Back to league management', 'shared.retry': 'Try again', 'shared.close': 'Close', 'shared.save': 'Save', 'shared.saving': 'Saving …', 'shared.edit': 'Edit', 'shared.action': 'Action', 'shared.status': 'Status', 'shared.active': 'Active', 'shared.inactive': 'Inactive',
  'drivers.denied': 'You need the league management role to manage drivers.', 'drivers.loading': 'Grid and driver assignments are loading.', 'drivers.loadingTitle': 'Loading drivers', 'drivers.loadError': 'Drivers could not be loaded.', 'drivers.loadErrorTitle': 'Drivers could not be loaded', 'drivers.created': 'Driver created.', 'drivers.updated': 'Driver updated.', 'drivers.saveError': 'Driver could not be saved.', 'drivers.title': 'Manage drivers', 'drivers.copy': 'Manage numbers, teams, cars and active drivers for the selected league. Existing results are not changed when editing.', 'drivers.create': 'Create driver', 'drivers.edit': 'Edit driver', 'drivers.new': 'New driver', 'drivers.displayName': 'Display name', 'drivers.gamertag': 'Gamertag', 'drivers.number': 'Driver number', 'drivers.nationality': 'Nationality', 'drivers.team': 'Team', 'drivers.car': 'Car', 'drivers.active': 'Active driver', 'drivers.activeHint': 'Show in selectors and current views.', 'drivers.save': 'Save driver', 'drivers.total': 'Total drivers', 'drivers.linked': 'Linked to account', 'drivers.grid': 'Grid', 'drivers.list': 'Drivers', 'drivers.teamCar': 'Team / car', 'drivers.results': 'Results', 'drivers.accountLinked': 'Account linked', 'drivers.noAccount': 'No account linked', 'drivers.noCar': 'No car', 'drivers.emptyTitle': 'No drivers yet', 'drivers.emptyCopy': 'Create the first driver to build the grid.',
  'import.denied': 'You need the league management role to import and publish results.', 'import.loading': 'Races, drivers and existing drafts are being prepared for review.', 'import.loadingTitle': 'Loading result import', 'import.workspaceLoadError': 'The import could not be loaded.', 'import.workspaceLoadErrorTitle': 'Result import could not be loaded', 'import.selectRaceError': 'Select the matching race first.', 'import.preparing': 'Preparing images (0/{count}) …', 'import.prepared': 'Prepared image {completed} of {total}: {file}', 'import.uploading': 'Images are being sent securely to the AI …', 'import.analysisDone': 'AI analysis completed: {count} result rows detected. Review the table and confirm the points.', 'import.draftSaved': 'Result draft reviewed and saved. Official data is still unchanged.', 'import.published': 'The result version was published officially.', 'import.publishError': 'The result could not be published.', 'import.analysisError': 'The AI could not analyze the images.', 'import.draftError': 'The draft could not be created.', 'import.title': 'Result import & release', 'import.copy': 'Read result screenshots with AI or import CSV data, review it clearly and save it as a revision-safe draft first.', 'import.selectRace': '1. Select race', 'import.chooseRace': 'Choose race', 'import.reason': '2. Change reason', 'import.reasonPlaceholder': 'e.g. result screenshots from race night', 'import.method': 'Import method', 'import.images': 'Images with AI', 'import.imagesHint': 'Recommended for in-game screenshots', 'import.csv': 'CSV file', 'import.csvHint': 'For prepared result tables', 'import.selectImages': 'Select result images', 'import.imagesCopy': 'Up to 8 screenshots are resized, transferred and read automatically.', 'import.imageLabel': 'Result images', 'import.imageSelected.one': '1 image selected · {files}', 'import.imageSelected.other': '{count} images selected · {files}', 'import.imageFormats': 'JPG, PNG, WebP, HEIC or HEIF · up to 20 MB per image', 'import.analyze': 'Read images', 'import.analyzing': 'Import running …', 'import.selectCsv': 'Select CSV file', 'import.csvCopy': 'Upload a prepared result table and review it before saving.', 'import.csvColumns': 'Driver, position, grid, points, team and optional stops and times', 'import.csvReadError': 'The CSV file could not be read.', 'import.checkCsv': 'Review CSV data', 'import.checkCsvHint': 'Adjust imported values directly here if needed.', 'import.waitingTitle': 'No results detected yet', 'import.waitingCopy': 'Select result images above and start the analysis. The editable table will appear here.', 'import.saveDraft': 'Save draft', 'import.officialUnchanged': 'Official results remain unchanged until the separate release.', 'import.release': 'Release', 'import.reviewedDrafts': 'Reviewed drafts', 'import.rows': '{count} result rows · {status}', 'import.publishNow': 'Publish officially now', 'import.noDraftsTitle': 'No open drafts', 'import.noDraftsCopy': 'All reviewed result versions are processed. New drafts appear here after saving.', 'import.aiWarnings': 'AI notes',
  'review.title': 'Review detected race data', 'review.copy': 'Every field can be edited directly. Drivers and points must be confirmed before saving.', 'review.rows': '{count} rows', 'review.mobileHint': 'Tap a driver to edit the assignment, positions, times and points.', 'review.position': 'Pos.', 'review.driver': 'Driver', 'review.match': 'Match', 'review.team': 'Team', 'review.grid': 'Grid', 'review.stops': 'Stops', 'review.fastestLap': 'Fastest lap', 'review.timeStatus': 'Time / status', 'review.points': 'Points', 'review.assignDriver': 'Assign driver', 'review.leagueDriver': 'League driver', 'review.finishPosition': 'Finish position', 'review.startPosition': 'Grid position', 'review.fastestLapFull': 'Fastest lap', 'review.raceTimeStatus': 'Race time or status', 'review.check': 'Review', 'review.assignmentMissing': 'Driver assignment missing', 'review.pointsMissing': 'Points missing', 'review.pointsShort': '{points} pts', 'review.tableLabel': 'Editable detected race results', 'review.mobileRowLabel': '{field} mobile row {row}', 'review.rowLabel': '{field} row {row}', 'review.detected': 'Detected: {driver}', 'review.confidence': '{confidence}% match confidence · {source}', 'review.manual': 'Selected manually', 'review.unassigned': 'Unassigned', 'review.similar': 'Similar name', 'review.gamertag': 'Gamertag', 'review.driverName': 'Driver name', 'review.inactive': 'inactive',
  'review.integerError': '{field} must be an integer of at least {minimum}.', 'review.emptyError': 'The review table contains no result rows.', 'review.assignAllError': 'Assign every detected driver to a league driver.', 'review.duplicateDriverError': 'A driver may only appear once per race.', 'review.duplicateFinishError': 'A finish position may only be assigned once.', 'review.driverUnavailableError': 'The driver in row {row} is no longer available.', 'review.pointsError': 'Review the points in row {row}.', 'review.fastestLapError': 'The fastest lap in row {row} is invalid.',
};

const es: Record<OperationsCopyKey, string> = {
  ...en,
  'import.reasonImages': 'Importación de resultados mediante análisis de imágenes con IA',
  'import.reasonCsv': 'Importación de resultados mediante CSV',
  'shared.scope': 'Dirección de liga · {league}', 'shared.deniedTitle': 'Acceso denegado', 'shared.back': 'Volver a la dirección de liga', 'shared.retry': 'Reintentar', 'shared.close': 'Cerrar', 'shared.save': 'Guardar', 'shared.saving': 'Guardando …', 'shared.edit': 'Editar', 'shared.action': 'Acción', 'shared.status': 'Estado', 'shared.active': 'Activo', 'shared.inactive': 'Inactivo',
  'drivers.denied': 'Necesitas el rol de dirección de liga para gestionar pilotos.', 'drivers.loading': 'Se están cargando la parrilla y las asignaciones de pilotos.', 'drivers.loadingTitle': 'Cargando pilotos', 'drivers.loadError': 'No se pudieron cargar los pilotos.', 'drivers.loadErrorTitle': 'No se pudieron cargar los pilotos', 'drivers.created': 'Piloto creado.', 'drivers.updated': 'Piloto actualizado.', 'drivers.saveError': 'No se pudo guardar el piloto.', 'drivers.title': 'Gestionar pilotos', 'drivers.copy': 'Gestiona dorsales, equipos, coches y pilotos activos de la liga seleccionada. Los resultados existentes no cambian al editar.', 'drivers.create': 'Crear piloto', 'drivers.edit': 'Editar piloto', 'drivers.new': 'Nuevo piloto', 'drivers.displayName': 'Nombre visible', 'drivers.gamertag': 'Gamertag', 'drivers.number': 'Dorsal', 'drivers.nationality': 'Nacionalidad', 'drivers.team': 'Equipo', 'drivers.car': 'Coche', 'drivers.active': 'Piloto activo', 'drivers.activeHint': 'Mostrar en selectores y vistas actuales.', 'drivers.save': 'Guardar piloto', 'drivers.total': 'Pilotos totales', 'drivers.linked': 'Vinculados a una cuenta', 'drivers.grid': 'Parrilla', 'drivers.list': 'Pilotos', 'drivers.teamCar': 'Equipo / coche', 'drivers.results': 'Resultados', 'drivers.accountLinked': 'Cuenta vinculada', 'drivers.noAccount': 'Sin cuenta vinculada', 'drivers.noCar': 'Sin coche', 'drivers.emptyTitle': 'Aún no hay pilotos', 'drivers.emptyCopy': 'Crea el primer piloto para formar la parrilla.',
  'import.denied': 'Necesitas el rol de dirección de liga para importar y publicar resultados.', 'import.loading': 'Se preparan carreras, pilotos y borradores para su revisión.', 'import.loadingTitle': 'Cargando importación de resultados', 'import.selectRaceError': 'Selecciona primero la carrera correspondiente.', 'import.uploading': 'Las imágenes se envían de forma segura a la IA …', 'import.analysisDone': 'Análisis de IA completado: {count} filas detectadas. Revisa la tabla y confirma los puntos.', 'import.draftSaved': 'Borrador revisado y guardado. Los datos oficiales siguen sin cambios.', 'import.published': 'La versión del resultado se publicó oficialmente.', 'import.publishError': 'No se pudo publicar el resultado.', 'import.title': 'Importación y publicación de resultados', 'import.copy': 'Lee capturas con IA o importa un CSV, revisa los datos y guárdalos primero como borrador seguro.', 'import.selectRace': '1. Seleccionar carrera', 'import.chooseRace': 'Elegir carrera', 'import.reason': '2. Motivo del cambio', 'import.reasonPlaceholder': 'p. ej., capturas de la noche de carrera', 'import.method': 'Método de importación', 'import.images': 'Imágenes con IA', 'import.imagesHint': 'Recomendado para capturas del juego', 'import.csv': 'Archivo CSV', 'import.csvHint': 'Para tablas de resultados preparadas', 'import.selectImages': 'Seleccionar imágenes de resultados', 'import.imagesCopy': 'Se reducen y analizan automáticamente hasta 8 capturas.', 'import.imageLabel': 'Imágenes de resultados', 'import.imageSelected.one': '1 imagen seleccionada · {files}', 'import.imageSelected.other': '{count} imágenes seleccionadas · {files}', 'import.imageFormats': 'JPG, PNG, WebP, HEIC o HEIF · máximo 20 MB por imagen', 'import.analyze': 'Leer imágenes', 'import.analyzing': 'Importando …', 'import.selectCsv': 'Seleccionar archivo CSV', 'import.csvCopy': 'Carga una tabla preparada y revísala antes de guardarla.', 'import.csvColumns': 'Piloto, posición, parrilla, puntos, equipo y paradas y tiempos opcionales', 'import.csvReadError': 'No se pudo leer el archivo CSV.', 'import.checkCsv': 'Revisar datos CSV', 'import.checkCsvHint': 'Ajusta aquí los valores importados si es necesario.', 'import.waitingTitle': 'Aún no hay resultados detectados', 'import.waitingCopy': 'Selecciona las imágenes y comienza el análisis. Después aparecerá la tabla editable.', 'import.saveDraft': 'Guardar borrador', 'import.officialUnchanged': 'Los resultados oficiales no cambian hasta la publicación separada.', 'import.release': 'Publicación', 'import.reviewedDrafts': 'Borradores revisados', 'import.rows': '{count} filas · {status}', 'import.publishNow': 'Publicar oficialmente', 'import.noDraftsTitle': 'No hay borradores abiertos', 'import.noDraftsCopy': 'Todos los borradores revisados están procesados. Los nuevos aparecerán aquí.',
  'review.title': 'Revisar datos detectados', 'review.copy': 'Todos los campos se pueden editar. Pilotos y puntos deben confirmarse antes de guardar.', 'review.mobileHint': 'Toca un piloto para editar asignación, posiciones, tiempos y puntos.', 'review.position': 'Pos.', 'review.driver': 'Piloto', 'review.team': 'Equipo', 'review.stops': 'Paradas', 'review.fastestLap': 'Vuelta rápida', 'review.timeStatus': 'Tiempo / estado', 'review.points': 'Puntos', 'review.assignDriver': 'Asignar piloto', 'review.detected': 'Detectado: {driver}', 'review.confidence': '{confidence}% de confianza · {source}', 'review.manual': 'Elegido manualmente', 'review.unassigned': 'Sin asignar', 'review.similar': 'Nombre similar', 'review.inactive': 'inactivo',
  'import.workspaceLoadError': 'No se pudo cargar la importación.', 'import.workspaceLoadErrorTitle': 'No se pudo cargar la importación de resultados', 'import.preparing': 'Preparando imágenes (0/{count}) …', 'import.prepared': 'Imagen {completed} de {total} preparada: {file}', 'import.analysisError': 'La IA no pudo analizar las imágenes.', 'import.draftError': 'No se pudo crear el borrador.', 'import.aiWarnings': 'Notas de la IA',
  'review.rows': '{count} filas', 'review.match': 'Coincidencia', 'review.grid': 'Parrilla', 'review.leagueDriver': 'Piloto de liga', 'review.finishPosition': 'Posición final', 'review.startPosition': 'Posición de salida', 'review.fastestLapFull': 'Vuelta rápida', 'review.raceTimeStatus': 'Tiempo de carrera o estado', 'review.check': 'Revisar', 'review.assignmentMissing': 'Falta asignar el piloto', 'review.pointsMissing': 'Faltan puntos', 'review.pointsShort': '{points} pts', 'review.tableLabel': 'Resultados detectados editables', 'review.mobileRowLabel': '{field} fila móvil {row}', 'review.rowLabel': '{field} fila {row}', 'review.gamertag': 'Gamertag', 'review.driverName': 'Nombre del piloto', 'review.integerError': '{field} debe ser un número entero de al menos {minimum}.', 'review.emptyError': 'La tabla de revisión no contiene resultados.', 'review.assignAllError': 'Asigna todos los pilotos detectados a un piloto de la liga.', 'review.duplicateDriverError': 'Un piloto solo puede aparecer una vez por carrera.', 'review.duplicateFinishError': 'Una posición final solo puede asignarse una vez.', 'review.driverUnavailableError': 'El piloto de la fila {row} ya no está disponible.', 'review.pointsError': 'Revisa los puntos de la fila {row}.', 'review.fastestLapError': 'La vuelta rápida de la fila {row} no es válida.',
};

const fr: Record<OperationsCopyKey, string> = {
  ...en,
  'import.reasonImages': 'Import des résultats par analyse d’images avec IA',
  'import.reasonCsv': 'Import des résultats par CSV',
  'shared.scope': 'Direction de ligue · {league}', 'shared.deniedTitle': 'Accès refusé', 'shared.back': 'Retour à la direction de ligue', 'shared.retry': 'Réessayer', 'shared.close': 'Fermer', 'shared.save': 'Enregistrer', 'shared.saving': 'Enregistrement …', 'shared.edit': 'Modifier', 'shared.action': 'Action', 'shared.status': 'Statut', 'shared.active': 'Actif', 'shared.inactive': 'Inactif',
  'drivers.denied': 'Le rôle de direction de ligue est nécessaire pour gérer les pilotes.', 'drivers.loading': 'La grille et les affectations des pilotes sont en cours de chargement.', 'drivers.loadingTitle': 'Chargement des pilotes', 'drivers.loadError': 'Les pilotes n’ont pas pu être chargés.', 'drivers.loadErrorTitle': 'Les pilotes n’ont pas pu être chargés', 'drivers.created': 'Pilote créé.', 'drivers.updated': 'Pilote mis à jour.', 'drivers.saveError': 'Le pilote n’a pas pu être enregistré.', 'drivers.title': 'Gérer les pilotes', 'drivers.copy': 'Gérez les numéros, équipes, voitures et pilotes actifs de la ligue. Les résultats existants ne changent pas lors de la modification.', 'drivers.create': 'Créer un pilote', 'drivers.edit': 'Modifier le pilote', 'drivers.new': 'Nouveau pilote', 'drivers.displayName': 'Nom affiché', 'drivers.gamertag': 'Gamertag', 'drivers.number': 'Numéro', 'drivers.nationality': 'Nationalité', 'drivers.team': 'Équipe', 'drivers.car': 'Voiture', 'drivers.active': 'Pilote actif', 'drivers.activeHint': 'Afficher dans les sélecteurs et vues actuelles.', 'drivers.save': 'Enregistrer le pilote', 'drivers.total': 'Total pilotes', 'drivers.linked': 'Liés à un compte', 'drivers.grid': 'Grille', 'drivers.list': 'Pilotes', 'drivers.teamCar': 'Équipe / voiture', 'drivers.results': 'Résultats', 'drivers.accountLinked': 'Compte lié', 'drivers.noAccount': 'Aucun compte lié', 'drivers.noCar': 'Aucune voiture', 'drivers.emptyTitle': 'Aucun pilote', 'drivers.emptyCopy': 'Créez le premier pilote pour constituer la grille.',
  'import.denied': 'Le rôle de direction de ligue est nécessaire pour importer et publier les résultats.', 'import.loading': 'Les courses, pilotes et brouillons sont préparés pour la vérification.', 'import.loadingTitle': 'Chargement de l’import', 'import.selectRaceError': 'Sélectionnez d’abord la course correspondante.', 'import.uploading': 'Les images sont envoyées à l’IA en toute sécurité …', 'import.analysisDone': 'Analyse IA terminée : {count} lignes détectées. Vérifiez le tableau et confirmez les points.', 'import.draftSaved': 'Brouillon vérifié et enregistré. Les données officielles restent inchangées.', 'import.published': 'La version du résultat a été publiée officiellement.', 'import.publishError': 'Le résultat n’a pas pu être publié.', 'import.title': 'Import et publication des résultats', 'import.copy': 'Lisez des captures avec l’IA ou importez un CSV, vérifiez les données puis enregistrez un brouillon sécurisé.', 'import.selectRace': '1. Sélectionner la course', 'import.chooseRace': 'Choisir la course', 'import.reason': '2. Motif de la modification', 'import.reasonPlaceholder': 'p. ex. captures de la soirée de course', 'import.method': 'Méthode d’import', 'import.images': 'Images avec IA', 'import.imagesHint': 'Recommandé pour les captures du jeu', 'import.csv': 'Fichier CSV', 'import.csvHint': 'Pour les tableaux de résultats préparés', 'import.selectImages': 'Sélectionner les images', 'import.imagesCopy': 'Jusqu’à 8 captures sont réduites, transférées et lues automatiquement.', 'import.imageLabel': 'Images des résultats', 'import.imageSelected.one': '1 image sélectionnée · {files}', 'import.imageSelected.other': '{count} images sélectionnées · {files}', 'import.imageFormats': 'JPG, PNG, WebP, HEIC ou HEIF · 20 Mo maximum par image', 'import.analyze': 'Lire les images', 'import.analyzing': 'Import en cours …', 'import.selectCsv': 'Sélectionner le fichier CSV', 'import.csvCopy': 'Chargez un tableau préparé et vérifiez-le avant l’enregistrement.', 'import.csvColumns': 'Pilote, position, grille, points, équipe et arrêts et temps facultatifs', 'import.csvReadError': 'Le fichier CSV n’a pas pu être lu.', 'import.checkCsv': 'Vérifier les données CSV', 'import.checkCsvHint': 'Ajustez ici les valeurs importées si nécessaire.', 'import.waitingTitle': 'Aucun résultat détecté', 'import.waitingCopy': 'Sélectionnez les images et lancez l’analyse. Le tableau modifiable apparaîtra ensuite.', 'import.saveDraft': 'Enregistrer le brouillon', 'import.officialUnchanged': 'Les résultats officiels restent inchangés jusqu’à la publication séparée.', 'import.release': 'Publication', 'import.reviewedDrafts': 'Brouillons vérifiés', 'import.rows': '{count} lignes · {status}', 'import.publishNow': 'Publier officiellement', 'import.noDraftsTitle': 'Aucun brouillon ouvert', 'import.noDraftsCopy': 'Tous les brouillons vérifiés sont traités. Les nouveaux apparaîtront ici.',
  'review.title': 'Vérifier les données détectées', 'review.copy': 'Tous les champs sont modifiables. Les pilotes et points doivent être confirmés avant l’enregistrement.', 'review.mobileHint': 'Touchez un pilote pour modifier l’affectation, les positions, les temps et les points.', 'review.position': 'Pos.', 'review.driver': 'Pilote', 'review.team': 'Équipe', 'review.stops': 'Arrêts', 'review.fastestLap': 'Meilleur tour', 'review.timeStatus': 'Temps / statut', 'review.points': 'Points', 'review.assignDriver': 'Affecter le pilote', 'review.detected': 'Détecté : {driver}', 'review.confidence': '{confidence}% de confiance · {source}', 'review.manual': 'Choisi manuellement', 'review.unassigned': 'Non affecté', 'review.similar': 'Nom similaire', 'review.inactive': 'inactif',
  'import.workspaceLoadError': 'L’import n’a pas pu être chargé.', 'import.workspaceLoadErrorTitle': 'L’import des résultats n’a pas pu être chargé', 'import.preparing': 'Préparation des images (0/{count}) …', 'import.prepared': 'Image {completed} sur {total} préparée : {file}', 'import.analysisError': 'L’IA n’a pas pu analyser les images.', 'import.draftError': 'Le brouillon n’a pas pu être créé.', 'import.aiWarnings': 'Notes de l’IA',
  'review.rows': '{count} lignes', 'review.match': 'Correspondance', 'review.grid': 'Grille', 'review.leagueDriver': 'Pilote de ligue', 'review.finishPosition': 'Position finale', 'review.startPosition': 'Position de départ', 'review.fastestLapFull': 'Meilleur tour', 'review.raceTimeStatus': 'Temps de course ou statut', 'review.check': 'Vérifier', 'review.assignmentMissing': 'Affectation du pilote manquante', 'review.pointsMissing': 'Points manquants', 'review.pointsShort': '{points} pts', 'review.tableLabel': 'Résultats détectés modifiables', 'review.mobileRowLabel': '{field} ligne mobile {row}', 'review.rowLabel': '{field} ligne {row}', 'review.gamertag': 'Gamertag', 'review.driverName': 'Nom du pilote', 'review.integerError': '{field} doit être un entier d’au moins {minimum}.', 'review.emptyError': 'Le tableau de vérification ne contient aucun résultat.', 'review.assignAllError': 'Affectez chaque pilote détecté à un pilote de la ligue.', 'review.duplicateDriverError': 'Un pilote ne peut apparaître qu’une fois par course.', 'review.duplicateFinishError': 'Une position finale ne peut être attribuée qu’une fois.', 'review.driverUnavailableError': 'Le pilote de la ligne {row} n’est plus disponible.', 'review.pointsError': 'Vérifiez les points de la ligne {row}.', 'review.fastestLapError': 'Le meilleur tour de la ligne {row} n’est pas valide.',
};

const dictionaries: Record<Language, Record<OperationsCopyKey, string>> = { de, en, es, fr };

function interpolate(template: string, values: Values = {}): string {
  return template.replace(/\{([a-zA-Z0-9_]+)\}/g, (match, key: string) => (
    Object.hasOwn(values, key) ? String(values[key]) : match
  ));
}

export function operationsCopyFor(language: Language): OperationsCopy {
  return (key, values) => interpolate(dictionaries[language][key], values);
}

export function useOperationsCopy(): OperationsCopy {
  const { language } = useI18n();
  return useCallback(
    operationsCopyFor(language),
    [language],
  );
}
