import type { Language } from '../i18n/I18nProvider';

const de = {
  title: 'Besetzung & Fahrzeugwechsel', substitute: 'Ersatzfahrer einsetzen', vehicle: 'Fahrzeug wechseln',
  profileHint: 'Team und Fahrzeug während der Saison bitte unten unter „Besetzung & Fahrzeugwechsel“ ändern.',
  ROSTER_USE_SUBSTITUTE: 'Für dieses Rennen ist eine Vertretung eingetragen. Wähle beim Import den tatsächlichen Ersatzfahrer statt des vertretenen Fahrers oder seines Bots.',
  ROSTER_DOUBLE_POINTS: 'Für denselben vertretenen Fahrer wurden mehrere Ergebnisse erkannt. Bitte die Fahrerzuordnung prüfen.',
  ROSTER_SEAT_OCCUPIED: 'Dieser F1-Sitz ist im gewählten Zeitraum bereits einem anderen Fahrer zugeordnet.',
  hint: 'Änderungen gelten nur für die aktive Saison. Veröffentlichte Ergebnisse bleiben unverändert.',
  race: 'Rennen', primary: 'Vertretener Fahrer · erhält die WM-Punkte', replacement: 'Ersatzfahrer · fährt das Rennen',
  choose: 'Bitte auswählen', saveSub: 'Ersatzfahrer speichern', remove: 'Vertretung aufheben',
  subHint: 'Nur dieses Rennen: Fahrer-WM-Punkte an den vertretenen Fahrer, Team-WM-Punkte an dessen Team. Beim Ergebnisimport den tatsächlichen Ersatzfahrer auswählen.',
  driver: 'Fahrer', from: 'Gültig ab Rennen', seat: 'Neues Fahrzeug / F1-Sitz', custom: 'F1-Sitz beibehalten',
  team: 'Team ab diesem Rennen', car: 'Fahrzeug ab diesem Rennen', saveVehicle: 'Fahrzeugwechsel speichern',
  vehicleHint: 'Gilt ab dem gewählten Rennen bis Saisonende. Frühere Rennen behalten die bisherige Zuordnung.',
  loading: 'Besetzungen werden geladen …', saving: 'Wird gespeichert …', saved: 'Änderung gespeichert.',
  error: 'Änderung nicht möglich. Bitte neu laden und die Auswahl prüfen.', retry: 'Erneut laden',
  empty: 'Keine aktive Saison vorhanden.', noOpen: 'Kein Rennen mehr für Änderungen offen.',
  locked: 'Gesperrt: Rennen abgeschlossen oder Ergebnisentwurf vorhanden.', history: 'Geplante Änderungen & Verlauf',
  noHistory: 'Noch keine Vertretung oder Fahrzeugänderung geplant.', round: 'Runde', for: 'fährt für',
  ROSTER_RACE_LOCKED: 'Für dieses oder ein späteres Rennen gibt es bereits ein Ergebnis oder einen Entwurf. Wähle eine spätere Runde.',
  ROSTER_HUMAN_REQUIRED: 'Wähle zwei unterschiedliche menschliche Fahrer aus dieser Liga.',
  ROSTER_DOUBLE_BOOKING: 'Einer dieser Fahrer ist für dieses Rennen bereits in einer anderen Vertretung eingetragen.',
  ROSTER_LATER_CHANGE_EXISTS: 'Es ist bereits ein späterer Wechsel geplant. Bearbeite zuerst diesen Wechsel.',
  ROSTER_VEHICLE_REQUIRED: 'Bitte Team und Fahrzeug angeben (jeweils höchstens 80 Zeichen).',
  ROSTER_ROUND_REQUIRED: 'Wähle ein Rennen aus der aktiven Saison.',
};
type Copy = Record<keyof typeof de, string>;
const en: Copy = {
  title: 'Line-up & vehicle changes', substitute: 'Assign substitute', vehicle: 'Change vehicle',
  profileHint: 'During the season, change team and vehicle below under “Line-up & vehicle changes”.',
  ROSTER_USE_SUBSTITUTE: 'A substitute is assigned for this race. Import the actual substitute instead of the represented driver or their bot.',
  ROSTER_DOUBLE_POINTS: 'Multiple results would credit the same represented driver. Check the driver assignments.',
  ROSTER_SEAT_OCCUPIED: 'This F1 seat is already assigned to another driver during the selected period.',
  hint: 'Changes apply to the active season only. Published results remain unchanged.',
  race: 'Race', primary: 'Represented driver · receives championship points', replacement: 'Substitute · races the car',
  choose: 'Please select', saveSub: 'Save substitute', remove: 'Cancel substitution',
  subHint: 'This race only: driver points go to the represented driver, team points to their team. Select the actual substitute when importing results.',
  driver: 'Driver', from: 'Effective from race', seat: 'New vehicle / F1 seat', custom: 'Keep F1 seat assignment',
  team: 'Team from this race', car: 'Vehicle from this race', saveVehicle: 'Save vehicle change',
  vehicleHint: 'Applies from the selected race to the season end. Earlier races retain their previous assignment.',
  loading: 'Loading line-ups …', saving: 'Saving …', saved: 'Change saved.',
  error: 'Unable to make this change. Reload and check your selection.', retry: 'Reload', empty: 'No active season.',
  noOpen: 'No races remain open for changes.', locked: 'Locked: race completed or result draft exists.',
  history: 'Scheduled changes & history', noHistory: 'No substitutions or vehicle changes yet.', round: 'Round', for: 'races for',
  ROSTER_RACE_LOCKED: 'This or a later race already has a result or draft. Select a later round.',
  ROSTER_HUMAN_REQUIRED: 'Select two different human drivers from this league.',
  ROSTER_DOUBLE_BOOKING: 'One of these drivers already has another substitution for this race.',
  ROSTER_LATER_CHANGE_EXISTS: 'A later change is already scheduled. Edit that change first.',
  ROSTER_VEHICLE_REQUIRED: 'Enter a team and vehicle (up to 80 characters each).', ROSTER_ROUND_REQUIRED: 'Select a race in the active season.',
};
const es: Copy = {
  title: 'Alineación y cambios de vehículo', substitute: 'Asignar suplente', vehicle: 'Cambiar vehículo',
  profileHint: 'Durante la temporada, cambia el equipo y vehículo abajo en «Alineación y cambios de vehículo».',
  ROSTER_USE_SUBSTITUTE: 'Hay un suplente asignado. Importa al suplente real, no al piloto representado ni a su bot.',
  ROSTER_DOUBLE_POINTS: 'Varios resultados asignan puntos al mismo piloto representado. Revisa las asignaciones.',
  ROSTER_SEAT_OCCUPIED: 'Este asiento F1 ya está asignado a otro piloto durante el periodo elegido.',
  hint: 'Los cambios solo afectan a la temporada activa. Los resultados publicados no cambian.',
  race: 'Carrera', primary: 'Piloto representado · recibe los puntos', replacement: 'Suplente · disputa la carrera',
  choose: 'Seleccionar', saveSub: 'Guardar suplente', remove: 'Cancelar sustitución',
  subHint: 'Solo esta carrera: los puntos de pilotos y equipos se asignan al piloto representado y a su equipo. Al importar, selecciona al suplente que corrió.',
  driver: 'Piloto', from: 'Válido desde la carrera', seat: 'Nuevo vehículo / asiento F1', custom: 'Mantener asiento F1',
  team: 'Equipo desde esta carrera', car: 'Vehículo desde esta carrera', saveVehicle: 'Guardar cambio',
  vehicleHint: 'Válido desde la carrera elegida hasta final de temporada. Las carreras anteriores conservan su asignación.',
  loading: 'Cargando alineaciones …', saving: 'Guardando …', saved: 'Cambio guardado.',
  error: 'No se puede realizar el cambio. Recarga y comprueba la selección.', retry: 'Recargar', empty: 'No hay temporada activa.',
  noOpen: 'No quedan carreras abiertas a cambios.', locked: 'Bloqueada: carrera completada o borrador de resultados existente.',
  history: 'Cambios programados e historial', noHistory: 'Aún no hay sustituciones ni cambios.', round: 'Ronda', for: 'corre por',
  ROSTER_RACE_LOCKED: 'Esta carrera u otra posterior ya tiene resultados o borrador. Elige una ronda posterior.',
  ROSTER_HUMAN_REQUIRED: 'Selecciona dos pilotos humanos distintos de esta liga.',
  ROSTER_DOUBLE_BOOKING: 'Uno de estos pilotos ya tiene otra sustitución para esta carrera.',
  ROSTER_LATER_CHANGE_EXISTS: 'Ya existe un cambio posterior. Edita ese cambio primero.',
  ROSTER_VEHICLE_REQUIRED: 'Indica equipo y vehículo (máximo 80 caracteres cada uno).', ROSTER_ROUND_REQUIRED: 'Selecciona una carrera de la temporada activa.',
};
const fr: Copy = {
  title: 'Composition et changements de véhicule', substitute: 'Désigner un remplaçant', vehicle: 'Changer de véhicule',
  profileHint: 'Pendant la saison, modifiez équipe et véhicule ci-dessous dans «Composition et changements de véhicule».',
  ROSTER_USE_SUBSTITUTE: 'Un remplaçant est désigné. Importez le remplaçant réel, pas le pilote représenté ni son bot.',
  ROSTER_DOUBLE_POINTS: 'Plusieurs résultats attribuent des points au même pilote représenté. Vérifiez les attributions.',
  ROSTER_SEAT_OCCUPIED: 'Ce baquet F1 est déjà attribué à un autre pilote pendant la période choisie.',
  hint: 'Les changements concernent uniquement la saison active. Les résultats publiés restent inchangés.',
  race: 'Course', primary: 'Pilote représenté · reçoit les points', replacement: 'Remplaçant · dispute la course',
  choose: 'Sélectionner', saveSub: 'Enregistrer le remplaçant', remove: 'Annuler le remplacement',
  subHint: 'Cette course uniquement : les points reviennent au pilote représenté et à son équipe. Lors de l’import, sélectionnez le remplaçant ayant couru.',
  driver: 'Pilote', from: 'À partir de la course', seat: 'Nouveau véhicule / baquet F1', custom: 'Conserver le baquet F1',
  team: 'Équipe à partir de cette course', car: 'Véhicule à partir de cette course', saveVehicle: 'Enregistrer le changement',
  vehicleHint: 'Valable de la course choisie à la fin de saison. Les courses précédentes conservent leur attribution.',
  loading: 'Chargement des compositions …', saving: 'Enregistrement …', saved: 'Changement enregistré.',
  error: 'Changement impossible. Rechargez et vérifiez la sélection.', retry: 'Recharger', empty: 'Aucune saison active.',
  noOpen: 'Aucune course encore ouverte aux changements.', locked: 'Verrouillée : course terminée ou brouillon de résultat existant.',
  history: 'Changements prévus et historique', noHistory: 'Aucun remplacement ou changement prévu.', round: 'Manche', for: 'court pour',
  ROSTER_RACE_LOCKED: 'Cette course ou une course ultérieure possède déjà un résultat ou brouillon. Choisissez une manche ultérieure.',
  ROSTER_HUMAN_REQUIRED: 'Sélectionnez deux pilotes humains différents de cette ligue.',
  ROSTER_DOUBLE_BOOKING: 'Un de ces pilotes a déjà un autre remplacement pour cette course.',
  ROSTER_LATER_CHANGE_EXISTS: 'Un changement ultérieur est déjà prévu. Modifiez-le en premier.',
  ROSTER_VEHICLE_REQUIRED: 'Indiquez une équipe et un véhicule (80 caractères maximum chacun).', ROSTER_ROUND_REQUIRED: 'Sélectionnez une course de la saison active.',
};
export const rosterCopies: Record<Language, Copy> = { de, en, es, fr };
export function rosterError(reason: unknown, language: Language): string {
  const message = reason instanceof Error ? reason.message : '';
  const copy = rosterCopies[language];
  if (message.includes('AI driver is already assigned')) return copy.ROSTER_SEAT_OCCUPIED;
  return Object.entries(copy).find(([key]) => key.startsWith('ROSTER_') && message.includes(key))?.[1] ?? copy.error;
}
