import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { AppState } from '../components/AppState';
import { useLeague } from '../league/LeagueProvider';
import { configureLeagueSeasonCalendar, loadSeasonSetupWorkspace, startLeagueSeason, type SeasonCalendarEntry, type SeasonGamePreset, type SeasonPlayerAssignment, type SeasonSetupWorkspace } from './operations';

type AssignmentDraft = { enabled: boolean; playerName: string; gamertag: string };
type WeatherMode = SeasonCalendarEntry['weather'];
type CalendarGenerationMode = 'manual' | 'random';
const WEEKDAYS = [{ value: 1, label: 'Mo' }, { value: 2, label: 'Di' }, { value: 3, label: 'Mi' }, { value: 4, label: 'Do' }, { value: 5, label: 'Fr' }, { value: 6, label: 'Sa' }, { value: 0, label: 'So' }];

function slugify(value: string) { return value.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); }
function localIsoDate(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; }
function nextSunday() { const date = new Date(); date.setHours(12, 0, 0, 0); date.setDate(date.getDate() + ((7 - date.getDay()) % 7)); return localIsoDate(date); }
function generateRaceDates(count: number, firstDate: string, weekdays: number[]) {
  const allowedDays = new Set(weekdays); const cursor = new Date(`${firstDate}T12:00:00`); const dates: string[] = [];
  for (let guard = 0; dates.length < count && guard < 3700; guard += 1) { if (allowedDays.has(cursor.getDay())) dates.push(localIsoDate(cursor)); cursor.setDate(cursor.getDate() + 1); }
  return dates;
}
function weatherForRound(mode: WeatherMode): SeasonCalendarEntry['weather'] { return mode; }
export function shuffledTracks<T>(tracks: readonly T[], random: () => number = Math.random): T[] {
  const shuffled = [...tracks];
  for (let index = shuffled.length - 1; index > 0; index -= 1) {
    const target = Math.floor(random() * (index + 1));
    [shuffled[index], shuffled[target]] = [shuffled[target], shuffled[index]];
  }
  return shuffled;
}
function buildCalendar(game: SeasonGamePreset, count: number, firstDate: string, weekdays: number[], time: string, weatherMode: WeatherMode, sprintCount: number, generationMode: CalendarGenerationMode = 'manual'): SeasonCalendarEntry[] {
  const safeCount = Math.max(1, Math.min(game.tracks.length, count)); const dates = generateRaceDates(safeCount, firstDate, weekdays); const sprintRounds = new Set<number>();
  if (sprintCount > 0) { const interval = safeCount / Math.min(safeCount, sprintCount); for (let index = 0; index < sprintCount; index += 1) sprintRounds.add(Math.min(safeCount - 1, Math.floor((index + 0.5) * interval))); }
  const tracks = generationMode === 'random' ? shuffledTracks(game.tracks) : game.tracks.slice();
  return tracks.slice(0, safeCount).map((track, index) => ({ track_key: track.key, date: dates[index] ?? '', time, weather: weatherForRound(weatherMode), has_sprint: sprintRounds.has(index) }));
}

export function SeasonSetupPage() {
  const { client } = useLeague(); const navigate = useNavigate();
  const [workspace, setWorkspace] = useState<SeasonSetupWorkspace | null>(null); const [step, setStep] = useState(1);
  const [name, setName] = useState(() => `Saison ${new Date().getFullYear()}`); const [slug, setSlug] = useState(() => `saison-${new Date().getFullYear()}`); const [slugTouched, setSlugTouched] = useState(false); const [gameKey, setGameKey] = useState('f1_25');
  const [assignments, setAssignments] = useState<Record<string, AssignmentDraft>>({}); const [raceCount, setRaceCount] = useState(24); const [firstRaceDate, setFirstRaceDate] = useState(nextSunday); const [raceTime, setRaceTime] = useState('20:00'); const [weekdays, setWeekdays] = useState<number[]>([0]); const [weatherMode, setWeatherMode] = useState<WeatherMode>('dynamisch'); const [fastestLapBonusEnabled, setFastestLapBonusEnabled] = useState<boolean | null>(null); const [sprintCount, setSprintCount] = useState(0); const [calendar, setCalendar] = useState<SeasonCalendarEntry[]>([]); const [generationMode, setGenerationMode] = useState<CalendarGenerationMode>('random');
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [loadAttempt, setLoadAttempt] = useState(0);

  useEffect(() => { let active = true; void loadSeasonSetupWorkspace(client).then((data) => {
    if (!active) return; const activeSeason = data.active_season; const initialGameKey = activeSeason?.game_key ?? data.games[0]?.key ?? 'f1_25'; const initialGame = data.games.find((item) => item.key === initialGameKey) ?? data.games[0];
    setWorkspace(data); setGameKey(initialGameKey); if (activeSeason) { setName(activeSeason.name); setSlug(activeSeason.slug); setSlugTouched(true); setFastestLapBonusEnabled(Boolean(activeSeason.fastest_lap_bonus_enabled)); setStep(3); }
    if (initialGame) { const existing = activeSeason?.calendar ?? []; const count = existing.length || initialGame.tracks.length; const firstExistingDate = existing.find((entry) => entry.date)?.date || nextSunday(); const initialCalendar = buildCalendar(initialGame, count, firstExistingDate, [0], '20:00', 'dynamisch', 0).map((entry, index) => ({ ...entry, ...(existing[index] ?? {}), track_key: existing[index]?.track_key || entry.track_key, date: existing[index]?.date || entry.date, time: existing[index]?.time || entry.time, weather: existing[index]?.weather || entry.weather })); setRaceCount(count); setFirstRaceDate(firstExistingDate); setCalendar(initialCalendar); setSprintCount(initialCalendar.filter((entry) => entry.has_sprint).length); setGenerationMode(existing.length ? 'manual' : 'random'); }
    setLoading(false);
  }).catch(() => { if (active) { setError('Die Saison-Einrichtung konnte nicht geladen werden.'); setLoading(false); } }); return () => { active = false; }; }, [client, loadAttempt]);

  const game = useMemo(() => workspace?.games.find((item) => item.key === gameKey) ?? workspace?.games[0], [gameKey, workspace]); const editingActive = Boolean(workspace?.active_season); const teamCount = useMemo(() => new Set((game?.roster ?? []).map((seat) => seat.team_name)).size, [game]);
  const playerAssignments = useMemo<SeasonPlayerAssignment[]>(() => (game?.roster ?? []).flatMap((seat) => { const draft = assignments[seat.seat_code]; return draft?.enabled ? [{ seat_code: seat.seat_code, player_name: draft.playerName.trim(), gamertag: draft.gamertag.trim() }] : []; }), [assignments, game]); const invalidAssignment = playerAssignments.some((item) => item.player_name.length < 2 || item.gamertag.length < 2); const flowStep = editingActive ? step - 2 : step; const flowTotal = editingActive ? 2 : 4;
  function updateAssignment(seatCode: string, update: Partial<AssignmentDraft>) { setAssignments((current) => { const existing = current[seatCode] ?? { enabled: false, playerName: '', gamertag: '' }; return { ...current, [seatCode]: { ...existing, ...update } }; }); }
  function updateCalendarEntry(index: number, update: Partial<SeasonCalendarEntry>) { setCalendar((current) => current.map((entry, entryIndex) => entryIndex === index ? { ...entry, ...update } : entry)); }
  function regenerateCalendar(mode: CalendarGenerationMode = generationMode) { if (!game) return; setError(''); if (!weekdays.length) { setError('Wähle mindestens einen Renntag aus.'); return; } setCalendar(buildCalendar(game, raceCount, firstRaceDate, weekdays, raceTime, weatherMode, sprintCount, mode)); }
  function continueFromSeason(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); if (name.trim().length < 3 || slug.trim().length < 3) { setError('Prüfe Saisonname und Kürzel.'); return; } setStep(2); }
  function continueFromGrid(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); if (invalidAssignment) { setError('Jeder zugeordnete Spieler benötigt einen Namen und einen Gamertag mit mindestens zwei Zeichen.'); return; } regenerateCalendar(); setStep(3); }
  function validateCalendar() { if (!game || calendar.length < 1 || calendar.length > game.tracks.length) return 'Die Rennanzahl ist ungültig.'; if (calendar.length !== raceCount) return 'Aktualisiere den Kalender nach der Änderung der Rennanzahl.'; const tracks = new Set<string>(); for (let index = 0; index < calendar.length; index += 1) { const entry = calendar[index]; if (!game.tracks.some((track) => track.key === entry.track_key)) return `Wähle für Rennen ${index + 1} eine Strecke.`; if (tracks.has(entry.track_key)) return `Die Strecke in Rennen ${index + 1} ist bereits im Kalender enthalten.`; tracks.add(entry.track_key); if (!/^\d{4}-\d{2}-\d{2}$/.test(entry.date)) return `Prüfe das Datum von Rennen ${index + 1}.`; if (!/^([01]\d|2[0-3]):[0-5]\d$/.test(entry.time)) return `Prüfe die Startzeit von Rennen ${index + 1}.`; } return ''; }
  function continueFromCalendar(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (fastestLapBonusEnabled === null) { setError('Lege fest, ob es den Extra-Punkt für die schnellste Runde geben soll.'); return; } const validationError = validateCalendar(); setError(validationError); if (!validationError) setStep(4); }
  async function saveSeason() { if (!game || invalidAssignment || fastestLapBonusEnabled === null) return; const validationError = validateCalendar(); if (validationError) { setError(validationError); setStep(3); return; } setBusy(true); setError(''); try { if (workspace?.active_season) { await configureLeagueSeasonCalendar(client, workspace.active_season.id, calendar, fastestLapBonusEnabled); navigate('/admin/races?calendarConfigured=1', { replace: true }); } else { await startLeagueSeason(client, { name: name.trim(), slug: slug.trim(), gameKey: game.key, startDate: calendar[0]?.date ?? '', fastestLapBonusEnabled, assignments: playerAssignments, calendar }); navigate('/admin?seasonStarted=1', { replace: true }); } } catch (reason) { setError(reason instanceof Error ? reason.message : editingActive ? 'Der Rennkalender konnte nicht gespeichert werden.' : 'Die Saison konnte nicht gestartet werden.'); setBusy(false); } }

  if (loading) return <AppState copy="Spiel, Starterfeld und Strecken werden geladen." title="Saison wird vorbereitet" tone="loading" />;
  if (!workspace || !game) return <AppState action={<button className="text-action" onClick={() => { setLoading(true); setError(''); setLoadAttempt((current) => current + 1); }} type="button">Erneut versuchen</button>} copy={error || 'Die benötigten Saisondaten stehen gerade nicht zur Verfügung.'} title="Saison-Einrichtung nicht verfügbar" tone="error" />;
  if (editingActive && !workspace.active_season?.calendar_can_configure) return <main className="onboarding-page" id="main-content"><section className="onboarding-card season-setup-card"><div className="onboarding-form"><div className="onboarding-section-heading"><h1>Kalender ist bereits im Rennbetrieb</h1><p>Für diese Saison existieren schon gefahrene Rennen oder Ergebnisse. Der Wizard überschreibt diese Daten deshalb nicht.</p></div><div className="onboarding-actions"><button className="primary-action" type="button" onClick={() => navigate('/admin/races')}>Rennen verwalten</button></div></div></section></main>;

  return <main className="onboarding-page season-setup-page" id="main-content"><section className="onboarding-card season-setup-card" aria-labelledby="season-setup-title">
    <header className="onboarding-header"><div><p className="section-label">{workspace.league.name} · Saison</p><h1 id="season-setup-title">{editingActive ? 'Rennkalender einrichten' : 'Saison startklar machen'}</h1><p>{editingActive ? `Lege jetzt Termine, Wetter und Rennumfang für ${workspace.active_season?.name} fest.` : 'RaceVora übernimmt das Starterfeld des Spiels. Du ordnest Spieler zu und planst anschließend den kompletten Rennkalender.'}</p></div><span className="onboarding-progress" aria-label={`Schritt ${flowStep} von ${flowTotal}`}>{flowStep}/{flowTotal}</span></header>
    <ol className={`onboarding-steps season-setup-steps${editingActive ? ' season-setup-steps--compact' : ''}`} aria-label="Schritte der Saison-Einrichtung">{!editingActive && <><li className={step >= 1 ? 'is-active' : ''} aria-current={step === 1 ? 'step' : undefined}><span>1</span>Saison</li><li className={step >= 2 ? 'is-active' : ''} aria-current={step === 2 ? 'step' : undefined}><span>2</span>Starterfeld</li></>}<li className={step >= 3 ? 'is-active' : ''} aria-current={step === 3 ? 'step' : undefined}><span>{editingActive ? 1 : 3}</span>Kalender</li><li className={step >= 4 ? 'is-active' : ''} aria-current={step === 4 ? 'step' : undefined}><span>{editingActive ? 2 : 4}</span>Prüfen</li></ol>

    {step === 1 && <form className="onboarding-form" onSubmit={continueFromSeason}><div className="onboarding-section-heading"><h2>Saison festlegen</h2><p>Wähle das Spiel; Fahrer, Fahrzeuge und Strecken werden daraus vorbereitet.</p></div><div className="onboarding-fields season-setup-fields"><label><span>Saisonname</span><input autoFocus required minLength={3} maxLength={80} value={name} onChange={(event) => { const next = event.target.value; setName(next); if (!slugTouched) setSlug(slugify(next)); }} /></label><label><span>Saison-Kürzel</span><input required minLength={3} maxLength={50} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={slug} onChange={(event) => { setSlugTouched(true); setSlug(slugify(event.target.value)); }} /></label><label><span>Spiel</span><select value={gameKey} onChange={(event) => { const nextKey = event.target.value; const nextGame = workspace.games.find((item) => item.key === nextKey); setGameKey(nextKey); setAssignments({}); setCalendar([]); setRaceCount(nextGame?.tracks.length ?? 1); }}>{workspace.games.map((preset) => <option key={preset.key} value={preset.key}>{preset.label}</option>)}</select></label></div><aside className="season-preset-summary" aria-live="polite"><strong>{game.label}</strong><span>{teamCount} Teams</span><span>{game.roster.length} Sitze</span><span>{game.tracks.length} Strecken</span><p>Rennanzahl, Termine, Wetter und Sprint-Wochenenden folgen im Kalender-Schritt.</p></aside>{error && <p className="form-error" role="alert">{error}</p>}<div className="onboarding-actions"><button className="primary-action" type="submit">Starterfeld einrichten</button></div></form>}

    {step === 2 && <form className="onboarding-form season-grid-form" onSubmit={continueFromGrid}><div className="onboarding-section-heading"><h2>Spieler den Sitzen zuordnen</h2><p>Ohne Zuordnung startet der offizielle KI-Fahrer. Aktiviere nur die Sitze echter Spieler.</p></div><div className="season-grid-summary"><strong>{playerAssignments.length} Spieler</strong><span>{game.roster.length - playerAssignments.length} KI-Fahrer</span></div><ol className="season-roster-list">{game.roster.map((seat) => { const draft = assignments[seat.seat_code] ?? { enabled: false, playerName: '', gamertag: '' }; return <li className={draft.enabled ? 'is-player' : ''} key={seat.seat_code}><div className="season-seat-number">#{seat.number}</div><div className="season-seat-copy"><strong>{seat.ai_driver_name}</strong><span>{seat.team_name} · {seat.car_name}</span></div><label className="season-player-toggle"><input checked={draft.enabled} type="checkbox" onChange={(event) => updateAssignment(seat.seat_code, { enabled: event.target.checked })} /><span>Spieler zuordnen</span></label>{draft.enabled && <div className="season-player-fields"><label><span>Spielername</span><input required minLength={2} maxLength={80} value={draft.playerName} onChange={(event) => updateAssignment(seat.seat_code, { playerName: event.target.value })} /></label><label><span>Gamertag</span><input required minLength={2} maxLength={80} value={draft.gamertag} onChange={(event) => updateAssignment(seat.seat_code, { gamertag: event.target.value })} /></label></div>}</li>; })}</ol>{error && <p className="form-error" role="alert">{error}</p>}<div className="onboarding-actions onboarding-actions--split"><button className="text-action" type="button" onClick={() => { setError(''); setStep(1); }}>Zurück</button><button className="primary-action" type="submit">Rennkalender einrichten</button></div></form>}

    {step === 3 && <form className="onboarding-form season-calendar-form" onSubmit={continueFromCalendar}><div className="onboarding-section-heading"><h2>Rennkalender planen</h2><p>Lege Saisonlänge, Renntage, Startzeit, Wetter und die Regel für die schnellste Runde fest. Danach wählst du zwischen einer zufälligen Streckenreihenfolge und der manuellen Tabelle.</p></div><div className="season-calendar-controls"><label><span>Anzahl Rennen</span><input min="1" max={game.tracks.length} type="number" value={raceCount} onChange={(event) => setRaceCount(Math.max(1, Math.min(game.tracks.length, Number(event.target.value) || 1)))} /><small>Maximal {game.tracks.length} Strecken</small></label><label><span>Erster Renntag</span><input type="date" value={firstRaceDate} onChange={(event) => setFirstRaceDate(event.target.value)} /></label><label><span>Standard-Uhrzeit</span><input type="time" value={raceTime} onChange={(event) => setRaceTime(event.target.value)} /></label><label><span>Wettervorgabe</span><select value={weatherMode} onChange={(event) => setWeatherMode(event.target.value as WeatherMode)}><option value="dynamisch">Wechselhaft</option><option value="klar">Trocken</option><option value="regen">Regen</option></select></label><label><span>Sprint-Wochenenden</span><input min="0" max={raceCount} type="number" value={sprintCount} onChange={(event) => setSprintCount(Math.max(0, Math.min(raceCount, Number(event.target.value) || 0)))} /></label></div>
      <fieldset className="season-calendar-mode season-fastest-lap-rule"><legend>Extra-Punkt für die schnellste Runde</legend><div className="season-calendar-mode-options"><label className={fastestLapBonusEnabled === true ? 'is-selected' : ''}><input checked={fastestLapBonusEnabled === true} name="fastest-lap-bonus" type="radio" onChange={() => setFastestLapBonusEnabled(true)} /><span><strong>Ja, +1 Punkt</strong><small>Der Fahrer erhält den Punkt nur mit der schnellsten Runde und einer Platzierung von P10 oder besser.</small></span></label><label className={fastestLapBonusEnabled === false ? 'is-selected' : ''}><input checked={fastestLapBonusEnabled === false} name="fastest-lap-bonus" type="radio" onChange={() => setFastestLapBonusEnabled(false)} /><span><strong>Nein</strong><small>Für die schnellste Runde wird in dieser Saison kein zusätzlicher Punkt vergeben.</small></span></label></div></fieldset>
      <fieldset className="season-calendar-weekdays"><legend>Renntage</legend><div>{WEEKDAYS.map((day) => <label className={weekdays.includes(day.value) ? 'is-selected' : ''} key={day.value}><input checked={weekdays.includes(day.value)} type="checkbox" onChange={(event) => setWeekdays((current) => event.target.checked ? [...current, day.value] : current.filter((value) => value !== day.value))} /><span>{day.label}</span></label>)}</div></fieldset>
      <fieldset className="season-calendar-mode"><legend>Streckenreihenfolge</legend><div className="season-calendar-mode-options"><label className={generationMode === 'random' ? 'is-selected' : ''}><input checked={generationMode === 'random'} name="calendar-generation-mode" type="radio" value="random" onChange={() => setGenerationMode('random')} /><span><strong>Zufällige Reihenfolge</strong><small>RaceVora mischt die ausgewählten Strecken bei jeder Erstellung neu.</small></span></label><label className={generationMode === 'manual' ? 'is-selected' : ''}><input checked={generationMode === 'manual'} name="calendar-generation-mode" type="radio" value="manual" onChange={() => setGenerationMode('manual')} /><span><strong>Manuell in Tabelle</strong><small>Alle Rennen werden gleichzeitig angezeigt und direkt bearbeitet.</small></span></label></div></fieldset>
      <div className="season-calendar-generate"><div><strong>{generationMode === 'random' ? 'Zufälligen Kalender erstellen' : 'Manuelle Tabelle vorbereiten'}</strong><p>Termine, Wetter und Sprintrennen folgen den Vorgaben oben. Jede Tabellenzeile bleibt anschließend editierbar.</p></div><button className="text-action" type="button" onClick={() => regenerateCalendar()}>{generationMode === 'random' ? 'Kalender zufällig mischen' : 'Tabelle aktualisieren'}</button></div>
      {calendar.length > 0 && <section className="season-calendar-table-section" aria-labelledby="season-calendar-table-title"><div className="season-calendar-table-heading"><div><strong id="season-calendar-table-title">Kompletter Rennkalender</strong><p>{calendar.length} Rennen geplant · Änderungen werden direkt übernommen.</p></div><span>{generationMode === 'random' ? 'Zufällig erstellt' : 'Manuelle Reihenfolge'}</span></div><div className="season-calendar-table-wrap" tabIndex={0} aria-label="Rennkalender horizontal scrollen"><table className="season-calendar-table"><thead><tr><th scope="col">Runde</th><th scope="col">Strecke</th><th scope="col">Datum</th><th scope="col">Startzeit</th><th scope="col">Wetter</th><th scope="col">Sprint</th></tr></thead><tbody>{calendar.map((entry, index) => <tr key={`${index}-${entry.track_key}`}><th scope="row">R{index + 1}</th><td><label className="sr-only" htmlFor={`calendar-track-${index}`}>Strecke Rennen {index + 1}</label><select id={`calendar-track-${index}`} aria-label={`Strecke Rennen ${index + 1}`} value={entry.track_key} onChange={(event) => updateCalendarEntry(index, { track_key: event.target.value })}>{game.tracks.map((track) => <option key={track.key} value={track.key}>{track.grand_prix_name}</option>)}</select></td><td><label className="sr-only" htmlFor={`calendar-date-${index}`}>Datum Rennen {index + 1}</label><input id={`calendar-date-${index}`} aria-label={`Datum Rennen ${index + 1}`} type="date" value={entry.date} onChange={(event) => updateCalendarEntry(index, { date: event.target.value })} /></td><td><label className="sr-only" htmlFor={`calendar-time-${index}`}>Startzeit Rennen {index + 1}</label><input id={`calendar-time-${index}`} aria-label={`Startzeit Rennen ${index + 1}`} type="time" value={entry.time} onChange={(event) => updateCalendarEntry(index, { time: event.target.value })} /></td><td><label className="sr-only" htmlFor={`calendar-weather-${index}`}>Wetter Rennen {index + 1}</label><select id={`calendar-weather-${index}`} aria-label={`Wetter Rennen ${index + 1}`} value={entry.weather} onChange={(event) => updateCalendarEntry(index, { weather: event.target.value as SeasonCalendarEntry['weather'] })}><option value="dynamisch">Wechselhaft</option><option value="klar">Trocken</option><option value="regen">Regen</option></select></td><td><label className="season-calendar-table-sprint"><input aria-label={`Sprint Rennen ${index + 1}`} checked={entry.has_sprint} type="checkbox" onChange={(event) => updateCalendarEntry(index, { has_sprint: event.target.checked })} /><span>Ja</span></label></td></tr>)}</tbody></table></div></section>}
      {error && <p className="form-error" role="alert">{error}</p>}<div className="onboarding-actions onboarding-actions--split">{!editingActive && <button className="text-action" type="button" onClick={() => { setError(''); setStep(2); }}>Zurück</button>}<button className="primary-action" type="submit">Kalender prüfen</button></div></form>}

    {step === 4 && <section className="onboarding-form season-review"><div className="onboarding-section-heading"><h2>{editingActive ? 'Kalender prüfen und speichern' : 'Prüfen und Saison starten'}</h2><p>{editingActive ? 'Die Termine und Saisonregeln werden erst mit deiner Bestätigung übernommen.' : 'Erst mit der Bestätigung werden Saison, Starterfeld, Regeln und Rennkalender gemeinsam gespeichert.'}</p></div><dl className="season-review-facts"><div><dt>Liga</dt><dd>{workspace.league.name}</dd></div><div><dt>Saison</dt><dd>{name}</dd></div><div><dt>Spiel</dt><dd>{game.label}</dd></div>{!editingActive && <div><dt>Starterfeld</dt><dd>{playerAssignments.length} Spieler · {game.roster.length - playerAssignments.length} KI-Fahrer</dd></div>}<div><dt>Rennkalender</dt><dd>{calendar.length} Rennen · {calendar.filter((entry) => entry.has_sprint).length} Sprints</dd></div><div><dt>Schnellste Runde</dt><dd>{fastestLapBonusEnabled ? '+1 Punkt bei P10 oder besser' : 'Kein Extra-Punkt'}</dd></div><div><dt>Erstes Rennen</dt><dd>{calendar[0]?.date} · {calendar[0]?.time} Uhr</dd></div></dl><aside className="season-start-note"><strong>{editingActive ? 'Bestehende Saison, neuer Kalender' : 'Start ist verbindlich'}</strong><p>{editingActive ? 'Nur der noch ungefahrene Kalender und seine Regeln werden ersetzt. Sobald Ergebnisse existieren, verhindert RaceVora ein Überschreiben.' : 'Fahrer, Fahrzeuge, Sitzzuordnungen, Saisonregeln und alle Renntermine werden als gemeinsamer Saisonstand gespeichert.'}</p></aside>{error && <p className="form-error" role="alert">{error}</p>}<div className="onboarding-actions onboarding-actions--split"><button className="text-action" disabled={busy} type="button" onClick={() => { setError(''); setStep(3); }}>Zurück</button><button className="primary-action" disabled={busy} type="button" onClick={() => void saveSeason()}>{busy ? 'Wird gespeichert …' : editingActive ? 'Kalender speichern' : 'Saison starten'}</button></div></section>}
  </section></main>;
}
