const de = {
  title: 'Liga-Teams', intro: 'Zwei Fahrer. Ein Team. Die Fahrzeuge bleiben unabhängig.', current: 'Laufende Saison', ai: 'KI',
  round: 'Änderungen gültig ab', chooseRound: 'Rennen ausdrücklich auswählen', view: 'Aktuelle Besetzung · nur Ansicht', roundWord: 'Rennen',
  raceHint: 'Die Übersicht zeigt die Besetzung ab diesem Rennen. Frühere Ergebnisse bleiben unverändert.',
  chooseHint: 'Wähle vor einer Änderung ausdrücklich ein noch nicht gefahrenes Rennen.',
  noSeason: 'Keine laufende Saison. Richte zuerst eine Saison ein und stelle danach ihre Teams zusammen.',
  noRounds: 'Kein unverändertes, noch nicht gefahrenes Rennen verfügbar.',
  create: 'Team erstellen', edit: 'Besetzung bearbeiten', editor: 'Team-Besetzung', name: 'Teamname', driver1: 'Fahrer 1', driver2: 'Fahrer 2',
  free: 'Freier Platz', noCar: 'Noch kein Fahrzeug', noTeam: 'Ohne Team', unassigned: 'Fahrer ohne Team', assign: 'Team bilden',
  move: 'Wechselt aus', departure: 'Neues Team für', destination: 'Neues Team auswählen',
  departureHint: 'Ein Fahrer kann das Team nur verlassen, wenn du hier direkt sein neues Team auswählst.',
  save: 'Besetzung speichern', saving: 'Wird gespeichert …', cancel: 'Abbrechen', saved: 'Team-Besetzung gespeichert.',
  vehicles: 'Die Fahrzeuge beider Fahrer bleiben unverändert.', empty: 'Noch keine Liga-Teams in dieser Ansicht.',
  loading: 'Team-Besetzungen werden geladen …', retry: 'Erneut laden', loadError: 'Teams konnten nicht geladen werden.',
  saveError: 'Die Besetzung wurde nicht gespeichert. Bitte prüfe die Angaben und versuche es erneut.',
  stale: 'Die Team- oder Renndaten wurden zwischenzeitlich geändert. Lade den aktuellen Stand neu und prüfe deine Auswahl.',
  full: 'Ein ausgewähltes Team hätte mehr als zwei Fahrer. Wähle ein anderes Zielteam oder tausche die Fahrer.',
  locked: 'Dieses Rennen ist inzwischen gesperrt oder es gibt eine spätere geplante Änderung. Bitte lade den aktuellen Stand neu.',
  duplicate: 'Diesen Teamnamen gibt es bereits.', invalid: 'Bitte wähle zwei unterschiedliche, aktive Fahrer deiner Liga.',
  reload: 'Aktuellen Stand laden', legacy: 'Weitere Teamdaten', legacyLink: 'Bisherige Teamdaten öffnen',
  legacyHint: 'Die bisherige Datenpflege bleibt erreichbar. Saisonwechsel führst du in der neuen Teamübersicht aus.',
  overfull: 'Mehr als zwei Fahrer: Bitte verteile die übrigen Fahrer zuerst auf andere Teams.',
  unassignedEmpty: 'Alle aktiven Fahrer sind einem Team zugeordnet.',
};
type Copy = typeof de;
const en: Copy = { ...de, title:'League teams',intro:'Two drivers. One team. Independent cars.',ai:'AI',current:'Current season',round:'Changes effective from',chooseRound:'Explicitly choose a race',view:'Current lineup · view only',roundWord:'Race',raceHint:'Lineups shown from this race. Earlier results stay unchanged.',chooseHint:'Explicitly choose an unplayed race before making changes.',noSeason:'No active season. Set up a season first, then choose its teams.',noRounds:'No untouched, unplayed race available.',create:'Create team',edit:'Edit lineup',editor:'Team lineup',name:'Team name',driver1:'Driver 1',driver2:'Driver 2',free:'Vacant seat',noCar:'No car assigned',noTeam:'No team',unassigned:'Drivers without a team',assign:'Form team',move:'Moving from',departure:'New team for',destination:'Choose a new team',departureHint:'A departing driver must be assigned to another team.',save:'Save lineup',saving:'Saving …',cancel:'Cancel',saved:'Team lineup saved.',vehicles:'Both drivers keep their cars.',empty:'No league teams in this view.',loading:'Loading team lineups …',retry:'Retry',loadError:'Could not load teams.',saveError:'Lineup was not saved. Check your choices and try again.',stale:'Team or race data changed. Reload and review your choices.',full:'A selected team would have more than two drivers. Choose another destination or swap drivers.',locked:'This race is locked or a later change is scheduled. Reload the current state.',duplicate:'That team name already exists.',invalid:'Choose different active drivers from this league.',reload:'Reload current state',legacy:'More team data',legacyLink:'Open previous team tools',legacyHint:'Previous data tools remain available. Use this overview for season changes.',overfull:'More than two drivers: move the extra drivers to other teams first.',unassignedEmpty:'All active drivers have a team.' };
const es: Copy = { ...en,title:'Equipos de la liga',intro:'Dos pilotos. Un equipo. Coches independientes.',ai:'IA',current:'Temporada actual',round:'Cambios a partir de',chooseRound:'Selecciona una carrera explícitamente',view:'Alineación actual · solo lectura',roundWord:'Carrera',raceHint:'Alineación desde esta carrera. Los resultados anteriores no cambian.',chooseHint:'Selecciona una carrera no disputada antes de realizar cambios.',noSeason:'Primero crea una temporada y después configura sus equipos.',noRounds:'No hay carreras sin disputar y sin resultados.',create:'Crear equipo',edit:'Editar alineación',editor:'Alineación del equipo',name:'Nombre del equipo',driver1:'Piloto 1',driver2:'Piloto 2',free:'Plaza libre',noCar:'Sin coche asignado',noTeam:'Sin equipo',unassigned:'Pilotos sin equipo',assign:'Formar equipo',move:'Procede de',departure:'Nuevo equipo para',destination:'Selecciona un nuevo equipo',departureHint:'Un piloto que sale debe pasar a otro equipo.',save:'Guardar alineación',saving:'Guardando …',cancel:'Cancelar',saved:'Alineación guardada.',vehicles:'Ambos pilotos conservan sus coches.',empty:'No hay equipos en esta vista.',loading:'Cargando alineaciones …',retry:'Reintentar',loadError:'No se pudieron cargar los equipos.',saveError:'No se guardó la alineación. Revisa los datos e inténtalo de nuevo.',stale:'Los datos han cambiado. Recarga y revisa tu selección.',full:'Un equipo tendría más de dos pilotos. Elige otro destino o intercambia pilotos.',locked:'Carrera bloqueada o cambio posterior programado. Recarga los datos.',duplicate:'Este nombre de equipo ya existe.',invalid:'Selecciona pilotos activos diferentes de esta liga.',reload:'Recargar datos',legacy:'Más datos de equipos',legacyLink:'Abrir herramientas anteriores',legacyHint:'Las herramientas anteriores siguen disponibles. Gestiona los cambios de temporada aquí.',overfull:'Más de dos pilotos: asigna primero los demás a otros equipos.',unassignedEmpty:'Todos los pilotos activos tienen equipo.' };
const fr: Copy = { ...en,title:'Équipes de la ligue',intro:'Deux pilotes. Une équipe. Des voitures indépendantes.',ai:'IA',current:'Saison en cours',round:'Changements à partir de',chooseRound:'Choisir explicitement une course',view:'Composition actuelle · lecture seule',roundWord:'Course',raceHint:'Composition à partir de cette course. Les résultats précédents restent inchangés.',chooseHint:'Choisissez une course non disputée avant toute modification.',noSeason:'Créez d’abord une saison, puis configurez ses équipes.',noRounds:'Aucune course non disputée et sans résultats disponible.',create:'Créer une équipe',edit:'Modifier la composition',editor:'Composition de l’équipe',name:'Nom de l’équipe',driver1:'Pilote 1',driver2:'Pilote 2',free:'Place libre',noCar:'Aucune voiture',noTeam:'Sans équipe',unassigned:'Pilotes sans équipe',assign:'Former une équipe',move:'Vient de',departure:'Nouvelle équipe pour',destination:'Choisir une nouvelle équipe',departureHint:'Un pilote sortant doit rejoindre une autre équipe.',save:'Enregistrer la composition',saving:'Enregistrement …',cancel:'Annuler',saved:'Composition enregistrée.',vehicles:'Les deux pilotes conservent leur voiture.',empty:'Aucune équipe dans cette vue.',loading:'Chargement des compositions …',retry:'Réessayer',loadError:'Impossible de charger les équipes.',saveError:'Composition non enregistrée. Vérifiez les choix et réessayez.',stale:'Les données ont changé. Rechargez et vérifiez vos choix.',full:'Une équipe aurait plus de deux pilotes. Choisissez une autre destination ou échangez les pilotes.',locked:'Course verrouillée ou changement ultérieur prévu. Rechargez les données.',duplicate:'Ce nom d’équipe existe déjà.',invalid:'Choisissez des pilotes actifs différents de cette ligue.',reload:'Recharger les données',legacy:'Autres données des équipes',legacyLink:'Ouvrir les anciens outils',legacyHint:'Les anciens outils restent accessibles. Gérez les changements de saison ici.',overfull:'Plus de deux pilotes : affectez les pilotes supplémentaires à d’autres équipes.',unassignedEmpty:'Tous les pilotes actifs ont une équipe.' };
export const teamManagerCopy = {
  de: { ...de, edit: 'Team bearbeiten', editor: 'Team bearbeiten' },
  en: { ...en, edit: 'Edit team', editor: 'Edit team' },
  es: { ...es, edit: 'Editar equipo', editor: 'Editar equipo' },
  fr: { ...fr, edit: 'Modifier l’équipe', editor: 'Modifier l’équipe' },
};
export const teamAssignmentCopy = {
  de: { assign: 'Team zuordnen', target: 'Team für', choose: 'Bestehendes Team auswählen', hint: 'Wähle ein Team mit freiem Platz. Ein neues Team legst du oben über „Team erstellen“ an.' },
  en: { assign: 'Assign team', target: 'Team for', choose: 'Choose an existing team', hint: 'Choose a team with a free seat. Use “Create team” above for a new team.' },
  es: { assign: 'Asignar equipo', target: 'Equipo para', choose: 'Seleccionar equipo existente', hint: 'Elige un equipo con plaza libre. Para uno nuevo, usa «Crear equipo» arriba.' },
  fr: { assign: 'Attribuer une équipe', target: 'Équipe pour', choose: 'Choisir une équipe existante', hint: 'Choisissez une équipe avec une place libre. Pour une nouvelle équipe, utilisez «Créer une équipe» en haut.' },
};
export function teamManagerError(reason: unknown, copy: Copy) {
  const message = reason && typeof reason === 'object' && 'message' in reason ? String(reason.message) : '';
  if (message.includes('TEAM_STATE_CHANGED')) return copy.stale;
  if (message.includes('TEAM_FULL')) return copy.full;
  if (message.includes('TEAM_NAME_EXISTS')) return copy.duplicate;
  if (message.includes('ROSTER_')) return copy.locked;
  if (message.includes('TEAM_DRIVERS_INVALID')) return copy.invalid;
  return copy.saveError;
}
