-- Race Control Center - Season & History migration
-- Run this in Supabase SQL Editor before using the new season features.

create table if not exists public.seasons (
  id bigint generated by default as identity primary key,
  name text not null unique,
  status text not null default 'active',
  is_current boolean not null default false,
  started_at timestamptz not null default now(),
  ended_at timestamptz
);

alter table public.races
  add column if not exists season_id bigint references public.seasons(id) on delete restrict;

create table if not exists public.championship_history (
  season_id bigint primary key references public.seasons(id) on delete cascade,
  season_name text,
  driver_champion text,
  constructor_champion text,
  created_at timestamptz not null default now()
);

insert into public.seasons (name, status, is_current)
select 'Saison 1', 'active', true
where not exists (select 1 from public.seasons);

update public.races
set season_id = (select id from public.seasons where is_current = true order by id desc limit 1)
where season_id is null;

create unique index if not exists seasons_one_current_idx
on public.seasons (is_current)
where is_current = true;
