begin;
select plan(15);
select has_function('public','get_league_configuration_workspace',array[]::text[],'configuration workspace exists');
select has_function('public','update_league_rules',array['jsonb','jsonb'],'rules write exists');
select has_function('public','rename_league_team',array['text','text','text'],'team write exists');
select has_function('public','create_league_result_draft',array['uuid','jsonb','text'],'result draft exists');
select has_function('public','publish_league_result_draft',array['uuid'],'result publish exists');
select function_privs_are('public','get_league_configuration_workspace',array[]::text[],'anon',array[]::text[],'anon configuration denied');
select function_privs_are('public','update_league_rules',array['jsonb','jsonb'],'anon',array[]::text[],'anon rules denied');
select function_privs_are('public','rename_league_team',array['text','text','text'],'anon',array[]::text[],'anon teams denied');
select function_privs_are('public','create_league_result_draft',array['uuid','jsonb','text'],'anon',array[]::text[],'anon drafts denied');
select function_privs_are('public','publish_league_result_draft',array['uuid'],'anon',array[]::text[],'anon publishing denied');
select ok(has_function_privilege('authenticated','public.get_league_configuration_workspace()','EXECUTE'),'guarded config reachable');
select ok(has_function_privilege('authenticated','public.update_league_rules(jsonb,jsonb)','EXECUTE'),'guarded rules reachable');
select ok(has_function_privilege('authenticated','public.rename_league_team(text,text,text)','EXECUTE'),'guarded teams reachable');
select ok(has_function_privilege('authenticated','public.create_league_result_draft(uuid,jsonb,text)','EXECUTE'),'guarded drafts reachable');
select ok(has_function_privilege('authenticated','public.publish_league_result_draft(uuid)','EXECUTE'),'guarded publishing reachable');
select * from finish();
rollback;
