import type { Language } from '../i18n/I18nProvider';
const de = {
  title: 'Weitere Gamertags', hint: 'Hinterlege die Namen, die in EA, PlayStation, Xbox oder Steam angezeigt werden. Sie gelten für deine verknüpften Fahrerprofile.',
  adminHint: 'Zusätzliche Namen gelten nur für dieses Fahrerprofil in dieser Liga. Persönliche Namen des verknüpften Kontos sind hier schreibgeschützt.',
  matchHint: 'Eindeutige Namen werden beim Import erkannt. Ähnliche oder mehrfach vergebene Namen müssen geprüft werden. Ergebnisse und XP bleiben unverändert.',
  loading: 'Gamertags werden geladen …', loadError: 'Gamertags konnten nicht geladen werden. Bitte erneut versuchen.', retry: 'Erneut versuchen',
  main: 'Haupt-Gamertag', personal: 'Persönlich', league: 'Diese Liga', readOnly: 'Im persönlichen Profil verwalten', empty: 'Noch keine weiteren Namen hinterlegt.',
  name: 'Weiterer Gamertag', platform: 'Plattform (optional)', add: 'Gamertag hinzufügen', remove: 'Entfernen', saving: 'Wird gespeichert …',
  saved: 'Gamertag gespeichert.', removed: 'Zusätzlicher Gamertag entfernt. Der Haupt-Gamertag bleibt unverändert.',
  duplicate: 'Dieser Name ist hier bereits hinterlegt.', limit: 'Es sind maximal 20 zusätzliche Namen möglich.', invalid: 'Bitte 2 bis 60 Zeichen ohne Steuerzeichen oder spitze Klammern eingeben.',
  saveError: 'Änderung nicht bestätigt. Prüfe die Verbindung und versuche es erneut; deine Eingabe bleibt erhalten.',
  platforms: { other: 'Keine Angabe', ea: 'EA', playstation: 'PlayStation / PSN', xbox: 'Xbox', steam: 'Steam' },
};
type Copy = { [K in keyof typeof de]: K extends 'platforms' ? Record<keyof typeof de.platforms, string> : string };
export const aliasCopy: Record<Language, Copy> = {
  de,
  en: { title: 'Additional gamertags', hint: 'Add the names shown in EA, PlayStation, Xbox or Steam. They apply to your linked driver profiles.', adminHint: 'Additional names apply only to this driver in this league. Personal account names are read-only here.', matchHint: 'Unique names are recognized during import. Similar or shared names require review. Results and XP stay unchanged.', loading: 'Loading gamertags …', loadError: 'Gamertags could not be loaded. Please try again.', retry: 'Try again', main: 'Main gamertag', personal: 'Personal', league: 'This league', readOnly: 'Manage in personal profile', empty: 'No additional names yet.', name: 'Additional gamertag', platform: 'Platform (optional)', add: 'Add gamertag', remove: 'Remove', saving: 'Saving …', saved: 'Gamertag saved.', removed: 'Additional gamertag removed. The main gamertag is unchanged.', duplicate: 'This name is already listed here.', limit: 'You can add up to 20 names.', invalid: 'Enter 2–60 characters without control characters or angle brackets.', saveError: 'Change not confirmed. Check your connection and retry; your input has been kept.', platforms: { ...de.platforms, other: 'Not specified' } },
  es: { title: 'Otros gamertags', hint: 'Añade los nombres que aparecen en EA, PlayStation, Xbox o Steam. Se aplican a tus perfiles de piloto vinculados.', adminHint: 'Estos nombres solo se aplican a este piloto en esta liga. Los nombres personales son de solo lectura aquí.', matchHint: 'Los nombres únicos se reconocen al importar. Los similares o compartidos requieren revisión. Los resultados y XP no cambian.', loading: 'Cargando gamertags …', loadError: 'No se pudieron cargar los gamertags. Inténtalo de nuevo.', retry: 'Reintentar', main: 'Gamertag principal', personal: 'Personal', league: 'Esta liga', readOnly: 'Gestionar en el perfil personal', empty: 'Todavía no hay otros nombres.', name: 'Otro gamertag', platform: 'Plataforma (opcional)', add: 'Añadir gamertag', remove: 'Eliminar', saving: 'Guardando …', saved: 'Gamertag guardado.', removed: 'Nombre adicional eliminado. El principal no cambia.', duplicate: 'Este nombre ya está registrado aquí.', limit: 'Puedes añadir hasta 20 nombres.', invalid: 'Introduce entre 2 y 60 caracteres sin caracteres de control ni corchetes angulares.', saveError: 'Cambio no confirmado. Comprueba la conexión y reintenta; se conserva tu entrada.', platforms: { ...de.platforms, other: 'Sin especificar' } },
  fr: { title: 'Autres gamertags', hint: 'Ajoutez les noms affichés dans EA, PlayStation, Xbox ou Steam. Ils concernent vos profils de pilote liés.', adminHint: 'Ces noms concernent uniquement ce pilote dans cette ligue. Les noms personnels sont en lecture seule ici.', matchHint: 'Les noms uniques sont reconnus à l’import. Les noms similaires ou partagés nécessitent une vérification. Résultats et XP inchangés.', loading: 'Chargement des gamertags …', loadError: 'Impossible de charger les gamertags. Réessayez.', retry: 'Réessayer', main: 'Gamertag principal', personal: 'Personnel', league: 'Cette ligue', readOnly: 'Gérer dans le profil personnel', empty: 'Aucun autre nom enregistré.', name: 'Autre gamertag', platform: 'Plateforme (facultative)', add: 'Ajouter un gamertag', remove: 'Retirer', saving: 'Enregistrement …', saved: 'Gamertag enregistré.', removed: 'Nom supplémentaire retiré. Le gamertag principal reste inchangé.', duplicate: 'Ce nom est déjà enregistré ici.', limit: 'Vous pouvez ajouter jusqu’à 20 noms.', invalid: 'Saisissez 2 à 60 caractères sans caractères de contrôle ni chevrons.', saveError: 'Modification non confirmée. Vérifiez la connexion et réessayez ; votre saisie est conservée.', platforms: { ...de.platforms, other: 'Non précisée' } },
};
