const de = {
  tracks: 'Strecken', track: 'Strecke', trackProfile: 'Streckenprofil', history: 'Historie', records: 'Rekorde', hall: 'Hall of Fame', archive: 'Saisonarchiv', rules: 'Regeln & FAQs', faq: 'FAQs', ruleHeading: 'Regeln', unspecified: 'Nicht festgelegt', emptyFaq: 'Noch keine FAQs hinterlegt.',
  emptyTracks: 'Für diesen Zeitraum sind noch keine gefahrenen Strecken vorhanden.', backTracks: 'Zur Streckenübersicht', withLap: 'Strecken mit Rundenzeit', facts: 'Streckendaten', leaders: 'Streckenrekorde', country: 'Land', type: 'Streckentyp', direction: 'Richtung', corners: 'Kurven', drs: 'DRS-Zonen', length: 'Länge', distance: 'Renndistanz', laps: 'F1-Runden', firstGP: 'Erster Grand Prix', f1Record: 'F1-Rundenrekord (Katalog)', bestLap: 'Liga-Bestzeit', winner: 'Sieger',
  comeback: 'Größte Aufholjagd', winStreak: 'Längste Siegesserie', podiumStreak: 'Längste Podiumsserie', pointsStreak: 'Längste Punkteserie', specialist: 'Streckenspezialist', average: 'Beste Ø-Zielposition', rate: 'Beste Zielankunftsquote', gained: 'Meiste Positionen gewonnen', consecutive: 'Starts in Folge', minThree: 'Mindestens 3 Starts', minFive: 'Mindestens 5 Starts', net: 'Netto über alle Starts', driverRecords: 'Fahrerrekorde', teamRecords: 'Teamrekorde', specialRecords: 'Besondere Leistungen',
  emptyArchive: 'Noch keine abgeschlossene Saison vorhanden.', archiveHint: 'Sobald eine Saison abgeschlossen wird, erscheint sie im Archiv.', withResults: 'Mit Ergebnis', resultRows: 'Ergebniszeilen', game: 'Spiel', openRace: 'Renndetails öffnen', emptyRaces: 'Für diese Saison sind keine Rennen hinterlegt.',
  currentChampions: 'Amtierende Champions', championHistory: 'Weltmeister-Historie', peopleTotals: 'Titel nach Fahrer', teamTotals: 'Titel nach Team', driverChampion: 'Fahrer-Weltmeister', teamChampion: 'Konstrukteurs-Weltmeister', championTeam: 'Team des Champions', lineup: 'Weltmeister-Lineup', historicSource: 'Archivdaten · Race Control Center', emptyHall: 'Noch keine Hall-of-Fame-Einträge für diese Liga vorhanden.', celebrate: 'Champions feiern', archived: 'Archiv',
  ai_strength: 'KI-Stärke', race_distance: 'Renndistanz', vehicle_performance: 'Fahrzeug-Performance', fastest_lap_point: 'Extra-Punkt für schnellste Runde', damage: 'Schaden', safety_car: 'Safety-Car-Wahrscheinlichkeit', red_flag: 'Red-Flag-Wahrscheinlichkeit', ghosting: 'Ghosting', assists: 'Fahrhilfen', qualifying: 'Qualifying', rulesError: 'Die Liga-Regeln konnten nicht geladen werden.', hallError: 'Die Hall of Fame konnte nicht geladen werden.',
};
type Copy = typeof de;
const en: Copy = {
  tracks: 'Tracks', track: 'Track', trackProfile: 'Track profile', history: 'History', records: 'Records', hall: 'Hall of Fame', archive: 'Season archive', rules: 'Rules & FAQs', faq: 'FAQs', ruleHeading: 'Rules', unspecified: 'Not specified', emptyFaq: 'No FAQs have been added yet.',
  emptyTracks: 'No raced tracks are available for this period.', backTracks: 'Back to tracks', withLap: 'Tracks with a lap time', facts: 'Track facts', leaders: 'Track records', country: 'Country', type: 'Track type', direction: 'Direction', corners: 'Corners', drs: 'DRS zones', length: 'Length', distance: 'Race distance', laps: 'F1 laps', firstGP: 'First Grand Prix', f1Record: 'F1 lap record (catalogue)', bestLap: 'League best lap', winner: 'Winner',
  comeback: 'Biggest comeback', winStreak: 'Longest winning streak', podiumStreak: 'Longest podium streak', pointsStreak: 'Longest points streak', specialist: 'Track specialist', average: 'Best average finish', rate: 'Best finish rate', gained: 'Most positions gained', consecutive: 'Consecutive starts', minThree: 'At least 3 starts', minFive: 'At least 5 starts', net: 'Net across all starts', driverRecords: 'Driver records', teamRecords: 'Team records', specialRecords: 'Special achievements',
  emptyArchive: 'No completed season yet.', archiveHint: 'Completed seasons will appear here.', withResults: 'With results', resultRows: 'Result rows', game: 'Game', openRace: 'Open race details', emptyRaces: 'No races in this season.',
  currentChampions: 'Reigning champions', championHistory: 'Championship history', peopleTotals: 'Titles by driver', teamTotals: 'Titles by team', driverChampion: 'Drivers’ champion', teamChampion: 'Constructors’ champion', championTeam: 'Champion’s team', lineup: 'Championship lineup', historicSource: 'Archive data · Race Control Center', emptyHall: 'No Hall of Fame entries for this league yet.', celebrate: 'Celebrate champions', archived: 'Archive',
  ai_strength: 'AI strength', race_distance: 'Race distance', vehicle_performance: 'Vehicle performance', fastest_lap_point: 'Extra point for fastest lap', damage: 'Damage', safety_car: 'Safety car probability', red_flag: 'Red flag probability', ghosting: 'Ghosting', assists: 'Assists', qualifying: 'Qualifying', rulesError: 'The league rules could not be loaded.', hallError: 'The Hall of Fame could not be loaded.',
};
const es: Copy = {
  tracks: 'Circuitos', track: 'Circuito', trackProfile: 'Perfil del circuito', history: 'Historial', records: 'Récords', hall: 'Salón de la Fama', archive: 'Archivo de temporadas', rules: 'Reglas y preguntas', faq: 'Preguntas frecuentes', ruleHeading: 'Reglas', unspecified: 'Sin definir', emptyFaq: 'Todavía no hay preguntas frecuentes.',
  emptyTracks: 'No hay circuitos disputados en este período.', backTracks: 'Volver a circuitos', withLap: 'Circuitos con tiempo de vuelta', facts: 'Datos del circuito', leaders: 'Récords del circuito', country: 'País', type: 'Tipo de circuito', direction: 'Sentido', corners: 'Curvas', drs: 'Zonas DRS', length: 'Longitud', distance: 'Distancia de carrera', laps: 'Vueltas F1', firstGP: 'Primer Gran Premio', f1Record: 'Récord F1 (catálogo)', bestLap: 'Mejor vuelta de la liga', winner: 'Ganador',
  comeback: 'Mayor remontada', winStreak: 'Mayor racha de victorias', podiumStreak: 'Mayor racha de podios', pointsStreak: 'Mayor racha de puntos', specialist: 'Especialista del circuito', average: 'Mejor posición media', rate: 'Mejor tasa de llegada', gained: 'Más posiciones ganadas', consecutive: 'Salidas consecutivas', minThree: 'Al menos 3 salidas', minFive: 'Al menos 5 salidas', net: 'Neto de todas las salidas', driverRecords: 'Récords de pilotos', teamRecords: 'Récords de equipos', specialRecords: 'Logros destacados',
  emptyArchive: 'Todavía no hay temporadas completadas.', archiveHint: 'Las temporadas completadas aparecerán aquí.', withResults: 'Con resultados', resultRows: 'Filas de resultados', game: 'Juego', openRace: 'Abrir detalles de carrera', emptyRaces: 'No hay carreras en esta temporada.',
  currentChampions: 'Campeones actuales', championHistory: 'Historial de campeones', peopleTotals: 'Títulos por piloto', teamTotals: 'Títulos por equipo', driverChampion: 'Campeón de pilotos', teamChampion: 'Campeón de constructores', championTeam: 'Equipo del campeón', lineup: 'Alineación campeona', historicSource: 'Datos de archivo · Race Control Center', emptyHall: 'Esta liga aún no tiene entradas en el Salón de la Fama.', celebrate: 'Celebrar campeones', archived: 'Archivo',
  ai_strength: 'Nivel de IA', race_distance: 'Distancia de carrera', vehicle_performance: 'Rendimiento del coche', fastest_lap_point: 'Punto extra por vuelta rápida', damage: 'Daños', safety_car: 'Probabilidad de coche de seguridad', red_flag: 'Probabilidad de bandera roja', ghosting: 'Ghosting', assists: 'Ayudas', qualifying: 'Clasificación', rulesError: 'No se pudieron cargar las reglas.', hallError: 'No se pudo cargar el Salón de la Fama.',
};
const fr: Copy = {
  tracks: 'Circuits', track: 'Circuit', trackProfile: 'Profil du circuit', history: 'Historique', records: 'Records', hall: 'Panthéon', archive: 'Archives des saisons', rules: 'Règles et FAQ', faq: 'FAQ', ruleHeading: 'Règles', unspecified: 'Non défini', emptyFaq: 'Aucune FAQ pour le moment.',
  emptyTracks: 'Aucun circuit disputé pour cette période.', backTracks: 'Retour aux circuits', withLap: 'Circuits avec un chrono', facts: 'Données du circuit', leaders: 'Records du circuit', country: 'Pays', type: 'Type de circuit', direction: 'Sens', corners: 'Virages', drs: 'Zones DRS', length: 'Longueur', distance: 'Distance de course', laps: 'Tours F1', firstGP: 'Premier Grand Prix', f1Record: 'Record F1 (catalogue)', bestLap: 'Meilleur tour de la ligue', winner: 'Vainqueur',
  comeback: 'Plus grande remontée', winStreak: 'Plus longue série de victoires', podiumStreak: 'Plus longue série de podiums', pointsStreak: 'Plus longue série de points', specialist: 'Spécialiste du circuit', average: 'Meilleure arrivée moyenne', rate: 'Meilleur taux d’arrivée', gained: 'Plus de places gagnées', consecutive: 'Départs consécutifs', minThree: 'Au moins 3 départs', minFive: 'Au moins 5 départs', net: 'Net sur tous les départs', driverRecords: 'Records pilotes', teamRecords: 'Records équipes', specialRecords: 'Performances remarquables',
  emptyArchive: 'Aucune saison terminée pour le moment.', archiveHint: 'Les saisons terminées apparaîtront ici.', withResults: 'Avec résultats', resultRows: 'Lignes de résultats', game: 'Jeu', openRace: 'Ouvrir les détails', emptyRaces: 'Aucune course dans cette saison.',
  currentChampions: 'Champions en titre', championHistory: 'Historique des champions', peopleTotals: 'Titres par pilote', teamTotals: 'Titres par équipe', driverChampion: 'Champion pilotes', teamChampion: 'Champion constructeurs', championTeam: 'Équipe du champion', lineup: 'Équipage champion', historicSource: 'Archives · Race Control Center', emptyHall: 'Cette ligue n’a pas encore d’entrée au Panthéon.', celebrate: 'Célébrer les champions', archived: 'Archives',
  ai_strength: 'Niveau IA', race_distance: 'Distance de course', vehicle_performance: 'Performance des voitures', fastest_lap_point: 'Point bonus du meilleur tour', damage: 'Dégâts', safety_car: 'Probabilité de voiture de sécurité', red_flag: 'Probabilité de drapeau rouge', ghosting: 'Ghosting', assists: 'Aides', qualifying: 'Qualifications', rulesError: 'Impossible de charger les règles.', hallError: 'Impossible de charger le Panthéon.',
};
export const historyMessages = { de, en, es, fr };
