import { Link } from 'react-router-dom';
import { driverStats, driverPerformance, position, teamNames, teamStats } from './profileData';
import { useRacingHistory, ProfileFrame, PeriodSelect, MissingSelection, ProfileTable, StatList, RaceLink, ProfileImage, type HistoryView } from './ProfileShared';
import { racingHref } from './calendarData';
import { CarLogo } from './RacingStandings';

function SeasonRows({ view, rows, team = false }: { view: HistoryView; rows: ReturnType<typeof driverStats>['seasons']; team?: boolean }) {
  const c = view.copy;
  return <ProfileTable view={view} headings={[c.seasonName, c.starts, c.wins, c.podiums, c.poles, c.fastestLaps, c.points, c.bestFinish]}>{rows.length ? rows.map((row) => <tr key={row.seasonId}><td><Link to={racingHref(team ? '/racing/teams/profile' : '/racing/drivers/profile', view.leagueSlug, { [team ? 'team' : 'driver']: view.params.get(team ? 'team' : 'driver') || '', season: row.seasonId })}>{row.seasonName}</Link></td>{[row.starts, row.wins, row.podiums, row.poles, row.fastestLaps, row.points, row.bestFinish].map((value, index) => <td key={index}>{value == null ? '—' : view.formatNumber(value)}</td>)}</tr>) : <tr><td colSpan={8}>{c.empty}</td></tr>}</ProfileTable>;
}
export function RacingDriverProfile() {
  const view = useRacingHistory(), { data, copy: c, params } = view;
  const drivers = [...data?.drivers || []].sort((a, b) => Number(b.is_active) - Number(a.is_active) || a.display_name.localeCompare(b.display_name));
  const id = params.get('driver') || drivers[0]?.id || '', seasonId = params.get('season') || '';
  const driver = drivers.find((item) => item.id === id);
  const valid = data && driver && (!seasonId || data.seasons.some((season) => season.id === seasonId));
  const stats = valid ? driverStats(data, id, seasonId) : null, performance = valid ? driverPerformance(data, id, seasonId) : null;
  const fmt = (value: number | null, digits = 0) => value == null ? '—' : new Intl.NumberFormat(view.language, { maximumFractionDigits: digits }).format(value);
  const score = performance?.score;
  const rating = score == null ? c.noRating : score >= 85 ? c.ratingTop : score >= 72 ? c.ratingStrong : score >= 60 ? c.ratingSolid : score >= 48 ? c.ratingMixed : c.ratingBuild;
  return <ProfileFrame view={view} title={c.driverTitle} kind="driver-profile">{data && <><div className="profile-controls"><label>{c.driver}<select value={id} onChange={(event) => view.choose('driver', event.target.value)}>{drivers.map((item) => <option key={item.id} value={item.id}>{item.display_name}</option>)}</select></label><PeriodSelect view={view} />{driver && <Link className="profile-action" to={racingHref('/career/compare', view.leagueSlug, { driver: id, ...(seasonId ? { season: seasonId } : {}) })}>{c.compare}</Link>}</div>{!valid || !stats || !performance ? <MissingSelection view={view} /> : <>
    <header className="profile-identity"><ProfileImage src={driver.avatar_url} alt={driver.display_name} className="profile-avatar" fallback={<span className="profile-initials" aria-hidden="true">{driver.display_name.split(/\s+/).slice(0, 2).map((part) => part[0]).join('')}</span>} /><div><p className="profile-meta">{/^[a-z]{2}$/i.test(driver.nationality_code || '') && <ProfileImage src={`/v1-assets/images/flags/${driver.nationality_code!.toLowerCase()}.svg`} alt={`${c.flag}: ${driver.nationality_code}`} className="profile-flag" fallback={null} />} {driver.nationality_code} {driver.gamertag ? ` · ${driver.gamertag}` : ''}</p><h2>{driver.display_name}</h2>{!driver.is_active && <p>{c.inactive}</p>}<p>{stats.snapshot?.league_team || c.noTeam}</p>{stats.snapshot?.car_name && <p>{stats.snapshot.car_name}</p>}</div><span className="profile-number">#{data.profileNumbers[id] ?? driver.number ?? '—'}</span></header>
    <StatList values={[[c.starts, fmt(stats.starts)], [c.wins, fmt(stats.wins)], [c.podiums, fmt(stats.podiums)], [c.poles, fmt(stats.poles)], [c.fastestLaps, fmt(stats.fastestLaps)], [c.points, fmt(stats.points)], [c.avgStart, fmt(stats.avgStart, 1)], [c.avgFinish, fmt(stats.avgFinish, 1)], [c.positionsGained, fmt(stats.positionsGained)], [c.bestFinish, stats.bestFinish == null ? '—' : `P${stats.bestFinish}`], [c.finishRate, stats.finishRate == null ? '—' : `${fmt(stats.finishRate * 100)} %`], [c.dnfs, fmt(stats.dnfs)]]} />
    <section className="profile-section"><h2>{c.performance}</h2><p className="profile-rating"><strong>{score == null ? '—' : `${score}/100`}</strong> {rating}</p><p>{c.sample}: {performance.sampleSize}</p><p>{performance.previousSampleSize >= 2 && performance.trend != null ? `${c.trend}: ${performance.trend > 0 ? '+' : ''}${performance.trend}` : c.insufficient}</p><dl className="profile-performance">{Object.entries(performance.components).map(([key, value]) => <div key={key}><dt>{c[key as keyof typeof performance.components]}</dt><dd>{value == null ? '—' : `${value}/100`}{value != null && <meter min={0} max={100} value={value} aria-label={c[key as keyof typeof performance.components]} />}</dd></div>)}</dl><p className="profile-method">{c.method}</p></section>
    <section className="profile-section"><h2>{c.form}</h2>{stats.recent.length ? <ol className="profile-form">{stats.recent.map((entry) => <li key={entry.race.id}><strong>{position(entry.row.finish_position) == null ? 'DNF' : `P${entry.row.finish_position}`}</strong><RaceLink view={view} race={entry.race} /></li>)}</ol> : <p>{c.empty}</p>}</section>
    <section className="profile-section"><h2>{c.seasons}</h2><SeasonRows view={{ ...view, params: new URLSearchParams({ driver: id }) }} rows={stats.seasons} /></section>
    <div className="profile-columns"><section className="profile-section"><h2>{c.tracks}</h2>{stats.tracks.length ? <ul className="profile-list">{stats.tracks.map((track) => <li key={track.name}><strong>{track.name}</strong><p>{c.starts}: {track.starts} · {c.wins}: {track.wins} · {c.podiums}: {track.podiums} · {c.bestFinish}: {track.bestFinish == null ? '—' : `P${track.bestFinish}`}</p></li>)}</ul> : <p>{c.empty}</p>}</section><section className="profile-section"><h2>{c.teams}</h2>{stats.teams.length ? <ul className="profile-list">{stats.teams.map((team) => <li key={`${team.team}:${team.car}`}><Link to={racingHref('/racing/teams/profile', view.leagueSlug, { team: team.team, ...(seasonId ? { season: seasonId } : {}) })}>{team.team}</Link><p>{team.car} · {c.starts}: {team.starts}</p></li>)}</ul> : <p>{c.empty}</p>}</section></div>
    <section className="profile-section"><h2>{c.recent}</h2><ProfileTable view={view} headings={[c.race, c.seasonName, c.start, c.finish, c.gain, c.points]}>{stats.recent.length ? stats.recent.map((entry) => <tr key={entry.race.id}><td><RaceLink view={view} race={entry.race} /></td><td>{data.seasons.find((season) => season.id === entry.race.season_id)?.name}</td><td>{position(entry.row.grid_position) ?? '—'}</td><td>{position(entry.row.finish_position) ?? 'DNF'}</td><td>{entry.gain ?? '—'}</td><td>{fmt(entry.points)}</td></tr>) : <tr><td colSpan={6}>{c.empty}</td></tr>}</ProfileTable></section>
  </>}</>}</ProfileFrame>;
}

export function RacingTeamProfile() {
  const view = useRacingHistory(), { data, copy: c, params } = view;
  const seasonId = params.get('season') || '';
  const names = data ? teamNames(data) : [];
  const name = params.get('team') || names[0] || '';
  const valid = data && names.some((item) => item.toLocaleLowerCase() === name.toLocaleLowerCase()) && (!seasonId || data.seasons.some((season) => season.id === seasonId));
  const stats = valid ? teamStats(data, name, seasonId) : null;
  return <ProfileFrame view={view} title={c.teamTitle} kind="team-profile">{data && <><div className="profile-controls"><label>{c.team}<select value={name} onChange={(event) => view.choose('team', event.target.value)}>{names.map((item) => <option key={item}>{item}</option>)}</select></label><PeriodSelect view={view} /></div>{!stats ? <MissingSelection view={view} /> : <>
    <header className="profile-identity"><CarLogo label={name} candidates={[stats.cars[0]?.name, name]} /><div><h2>{name}</h2><p>{stats.cars.map((car) => car.name).join(' · ') || '—'}</p></div><span>{c.bestFinish}: {stats.bestFinish == null ? '—' : `P${stats.bestFinish}`}</span></header>
    <StatList values={[[c.race, stats.races], [c.starts, stats.starts], [c.wins, stats.wins], [c.podiums, stats.podiums], [c.poles, stats.poles], [c.points, stats.points]]} />
    <div className="profile-columns"><section className="profile-section"><h2>{c.driver}</h2>{stats.drivers.length ? <ul className="profile-list">{stats.drivers.map((driver) => <li key={driver.driverId}><Link to={racingHref('/racing/drivers/profile', view.leagueSlug, { driver: driver.driverId, ...(seasonId ? { season: seasonId } : {}) })}>{driver.name}</Link><p>{c.starts}: {driver.starts} · {c.wins}: {driver.wins} · {c.podiums}: {driver.podiums} · {c.points}: {driver.points}</p></li>)}</ul> : <p>{c.empty}</p>}</section><section className="profile-section"><h2>{c.cars}</h2>{stats.cars.length ? <ul className="profile-list">{stats.cars.map((car) => <li key={car.name}><CarLogo candidates={[car.name, name]} label={car.name} /><p>{car.name} · {c.starts}: {car.starts}</p></li>)}</ul> : <p>{c.empty}</p>}</section></div>
    <section className="profile-section"><h2>{c.seasons}</h2><ProfileTable view={view} headings={[c.seasonName, c.race, c.starts, c.wins, c.podiums, c.poles, c.fastestLaps, c.points, c.bestFinish]}>{stats.seasons.length ? stats.seasons.map((season) => <tr key={season.seasonId}><td><Link to={racingHref('/racing/teams/profile', view.leagueSlug, { team: name, season: season.seasonId })}>{season.seasonName}</Link></td>{[season.races, season.starts, season.wins, season.podiums, season.poles, season.fastestLaps, season.points, season.bestFinish].map((n, i) => <td key={i}>{n ?? '—'}</td>)}</tr>) : <tr><td colSpan={9}>{c.empty}</td></tr>}</ProfileTable></section>
    <section className="profile-section"><h2>{c.recent}</h2><ProfileTable view={view} headings={[c.race, c.seasonName, c.bestFinish, c.driver, c.points]}>{stats.recent.length ? stats.recent.map((entry) => <tr key={entry.race.id}><td><RaceLink view={view} race={entry.race} /></td><td>{data.seasons.find((season) => season.id === entry.race.season_id)?.name}</td><td>{entry.bestFinish ?? '—'}</td><td>{entry.drivers.map((driver, index) => <span key={driver.driverId}>{index ? ' · ' : ''}<Link to={racingHref('/racing/drivers/profile', view.leagueSlug, { driver: driver.driverId, ...(seasonId ? { season: seasonId } : {}) })}>{driver.name}</Link></span>)}</td><td>{entry.points}</td></tr>) : <tr><td colSpan={5}>{c.empty}</td></tr>}</ProfileTable></section>
  </>}</>}</ProfileFrame>;
}
