const de = {
  title: 'Ergebnisse', subtitle: 'Alle Fahrer über alle Rennen inkl. Punkteverlauf.', matrix: 'Punkteübersicht der Saison', races: 'gewertete Rennen', drivers: 'Fahrer', total: 'Total', car: 'Auto',
  loading: 'Saisonergebnisse werden geladen …', error: 'Die Saisonergebnisse konnten nicht geladen werden. Bitte prüfe deine Verbindung und versuche es erneut.', retry: 'Erneut versuchen',
  noSeason: 'Keine aktive Saison', noSeasonCopy: 'Für diese Liga ist aktuell keine aktive Saison eingerichtet. Sobald eine Saison aktiviert wurde, erscheinen hier Ergebnisse und Punkteverläufe.', empty: 'Noch keine veröffentlichten Ergebnisse vorhanden.',
  fastest: 'Fastest Lap', fastestLabel: 'Schnellste Runde in diesem Rennen', bot: 'BOT gefahren', botLabel: 'Dieses Ergebnis wurde von einem Bot gefahren',
  trend: 'Punkteverlauf', trendCopy: 'Kumulierte Punkte über die Saison.', gap: 'WM-Dynamik', gapCopy: 'Punkteabstand zur Meisterschaftsführung.', gapNote: '0 Punkte entspricht der jeweiligen Meisterschaftsführung.',
  focus: 'Punkteverlauf filtern', leaders: 'Spitze', own: 'Mein Fahrer', compare: 'Vergleich', first: 'Ersten Vergleichsfahrer auswählen', second: 'Zweiten Vergleichsfahrer auswählen', choose: 'Fahrer wählen',
  noOwn: 'Für dieses Konto ist in der aktiven Liga kein Fahrerprofil verknüpft.', ownError: 'Dein Fahrerprofil konnte nicht geladen werden. Spitze und Vergleich bleiben verfügbar.', ownRetry: 'Fahrerprofil erneut laden',
  values: 'Diagrammwerte als Tabelle', chartError: 'Das Diagramm konnte nicht angezeigt werden. Die Werte sind weiterhin als Tabelle verfügbar.', chartRetry: 'Diagramm erneut laden', scroll: 'Ergebnistabelle horizontal scrollen', points: 'Punkte',
};
export type ResultsCopy = typeof de;
export const resultsMessages: Record<'de' | 'en' | 'es' | 'fr', ResultsCopy> = {
  de,
  en: {
    title: 'Results', subtitle: 'Every driver across all races, including points progression.', matrix: 'Season points overview', races: 'scored races', drivers: 'Drivers', total: 'Total', car: 'Car',
    loading: 'Loading season results …', error: 'Season results could not be loaded. Please check your connection and try again.', retry: 'Try again', noSeason: 'No active season', noSeasonCopy: 'This league has no active season. Results and points progression will appear when a season is activated.', empty: 'No published results yet.',
    fastest: 'Fastest Lap', fastestLabel: 'Fastest lap in this race', bot: 'BOT driven', botLabel: 'This result was driven by a bot', trend: 'Points progression', trendCopy: 'Cumulative points throughout the season.', gap: 'Championship dynamics', gapCopy: 'Points gap to the championship leader.', gapNote: '0 points represents the championship lead at each race.',
    focus: 'Filter points progression', leaders: 'Leaders', own: 'My driver', compare: 'Compare', first: 'Choose first comparison driver', second: 'Choose second comparison driver', choose: 'Choose driver', noOwn: 'No driver profile is linked to this account in the active league.', ownError: 'Your driver profile could not be loaded. Leaders and comparison remain available.', ownRetry: 'Reload driver profile', values: 'Chart values as a table', chartError: 'The chart could not be displayed. Its values remain available as a table.', chartRetry: 'Reload chart', scroll: 'Scroll results table horizontally', points: 'Points',
  },
  es: {
    title: 'Resultados', subtitle: 'Todos los pilotos y carreras, incluida la evolución de puntos.', matrix: 'Resumen de puntos de la temporada', races: 'carreras puntuadas', drivers: 'Pilotos', total: 'Total', car: 'Coche', loading: 'Cargando resultados de la temporada …', error: 'No se pudieron cargar los resultados. Comprueba tu conexión e inténtalo de nuevo.', retry: 'Reintentar', noSeason: 'Sin temporada activa', noSeasonCopy: 'Esta liga no tiene una temporada activa. Los resultados aparecerán cuando se active una temporada.', empty: 'Todavía no hay resultados publicados.', fastest: 'Vuelta rápida', fastestLabel: 'Vuelta más rápida de esta carrera', bot: 'Conducido por BOT', botLabel: 'Este resultado fue obtenido por un bot', trend: 'Evolución de puntos', trendCopy: 'Puntos acumulados durante la temporada.', gap: 'Dinámica del campeonato', gapCopy: 'Diferencia de puntos respecto al líder.', gapNote: '0 puntos representa el liderato en cada carrera.', focus: 'Filtrar evolución de puntos', leaders: 'Líderes', own: 'Mi piloto', compare: 'Comparar', first: 'Elegir primer piloto para comparar', second: 'Elegir segundo piloto para comparar', choose: 'Elegir piloto', noOwn: 'Esta cuenta no tiene un piloto vinculado en la liga activa.', ownError: 'No se pudo cargar tu piloto. Los líderes y la comparación siguen disponibles.', ownRetry: 'Recargar piloto', values: 'Valores del gráfico como tabla', chartError: 'No se pudo mostrar el gráfico. Los valores siguen disponibles en una tabla.', chartRetry: 'Recargar gráfico', scroll: 'Desplazar la tabla de resultados horizontalmente', points: 'Puntos',
  },
  fr: {
    title: 'Résultats', subtitle: 'Tous les pilotes et toutes les courses, avec évolution des points.', matrix: 'Points de la saison', races: 'courses comptabilisées', drivers: 'Pilotes', total: 'Total', car: 'Voiture', loading: 'Chargement des résultats de la saison …', error: 'Impossible de charger les résultats. Vérifiez votre connexion et réessayez.', retry: 'Réessayer', noSeason: 'Aucune saison active', noSeasonCopy: 'Cette ligue ne possède aucune saison active. Les résultats apparaîtront après activation d’une saison.', empty: 'Aucun résultat publié pour le moment.', fastest: 'Meilleur tour', fastestLabel: 'Meilleur tour de cette course', bot: 'Piloté par BOT', botLabel: 'Ce résultat a été obtenu par un bot', trend: 'Évolution des points', trendCopy: 'Points cumulés au cours de la saison.', gap: 'Dynamique du championnat', gapCopy: 'Écart de points avec le leader.', gapNote: '0 point représente la tête du championnat à chaque course.', focus: 'Filtrer l’évolution des points', leaders: 'Leaders', own: 'Mon pilote', compare: 'Comparer', first: 'Choisir le premier pilote à comparer', second: 'Choisir le deuxième pilote à comparer', choose: 'Choisir un pilote', noOwn: 'Aucun pilote de la ligue active n’est lié à ce compte.', ownError: 'Impossible de charger votre pilote. Les leaders et la comparaison restent disponibles.', ownRetry: 'Recharger le pilote', values: 'Valeurs du graphique en tableau', chartError: 'Impossible d’afficher le graphique. Les valeurs restent disponibles dans un tableau.', chartRetry: 'Recharger le graphique', scroll: 'Faire défiler horizontalement les résultats', points: 'Points',
  },
};
