const de = {
  driversTitle: 'Fahrer-Weltmeisterschaft', teamsTitle: 'Team-Weltmeisterschaft', drivers: 'Fahrer-WM', teams: 'Team-WM', total: 'Gesamtstand',
  subtitle: 'Automatische Wertung aus den veröffentlichten Rennergebnissen.', season: 'Saison', driverCount: 'Fahrer', teamCount: 'Teams',
  position: 'Pos', trend: 'Tendenz', driver: 'Fahrer', team: 'Liga-Team', car: 'Auto', wins: 'Siege', podiums: 'Podien', fastest: 'Schnellste Runden', points: 'Punkte',
  more: 'Weitere Statistiken anzeigen', less: 'Nur Position, Fahrer und Punkte anzeigen', loading: 'Meisterschaft wird geladen…',
  error: 'Die Meisterschaft konnte nicht geladen werden. Bitte prüfe deine Verbindung und versuche es erneut.', retry: 'Erneut versuchen',
  noSeason: 'Aktuell läuft keine Saison.', archive: 'Abgeschlossene Wertungen findest du im Saisonarchiv.', emptyDrivers: 'Noch keine Fahrerdaten vorhanden.', emptyTeams: 'Noch keine Teamdaten vorhanden.',
  flat: 'Keine Veränderung', up: 'Platz verbessert', down: 'Platz verloren', new: 'Neu in der Wertung', scroll: 'Meisterschaftstabelle, seitlich scrollbar', noTeam: 'Ohne Team',
};
type Copy = { [K in keyof typeof de]: string };
export const standingsMessages: Record<'de' | 'en' | 'es' | 'fr', Copy> = {
  de,
  en: { driversTitle: 'Drivers’ Championship', teamsTitle: 'Teams’ Championship', drivers: 'Drivers', teams: 'Teams', total: 'Overall standings', subtitle: 'Automatic standings from published race results.', season: 'Season', driverCount: 'drivers', teamCount: 'teams', position: 'Pos', trend: 'Trend', driver: 'Driver', team: 'League team', car: 'Car', wins: 'Wins', podiums: 'Podiums', fastest: 'Fastest laps', points: 'Points', more: 'Show more statistics', less: 'Show only position, driver and points', loading: 'Loading championship…', error: 'The championship could not be loaded. Check your connection and try again.', retry: 'Try again', noSeason: 'There is no active season.', archive: 'Completed standings are in the season archive.', emptyDrivers: 'No driver data yet.', emptyTeams: 'No team data yet.', flat: 'No change', up: 'Position gained', down: 'Position lost', new: 'New in the standings', scroll: 'Championship table, scroll horizontally', noTeam: 'No team' },
  es: { driversTitle: 'Campeonato de pilotos', teamsTitle: 'Campeonato de equipos', drivers: 'Pilotos', teams: 'Equipos', total: 'Clasificación general', subtitle: 'Clasificación automática a partir de los resultados publicados.', season: 'Temporada', driverCount: 'pilotos', teamCount: 'equipos', position: 'Pos', trend: 'Tendencia', driver: 'Piloto', team: 'Equipo de liga', car: 'Coche', wins: 'Victorias', podiums: 'Podios', fastest: 'Vueltas rápidas', points: 'Puntos', more: 'Mostrar más estadísticas', less: 'Mostrar solo posición, piloto y puntos', loading: 'Cargando campeonato…', error: 'No se pudo cargar el campeonato. Comprueba tu conexión e inténtalo de nuevo.', retry: 'Reintentar', noSeason: 'No hay una temporada activa.', archive: 'Las clasificaciones anteriores están en el archivo de temporadas.', emptyDrivers: 'Todavía no hay datos de pilotos.', emptyTeams: 'Todavía no hay datos de equipos.', flat: 'Sin cambios', up: 'Posición ganada', down: 'Posición perdida', new: 'Nuevo en la clasificación', scroll: 'Tabla del campeonato, desplazamiento horizontal', noTeam: 'Sin equipo' },
  fr: { driversTitle: 'Championnat des pilotes', teamsTitle: 'Championnat des équipes', drivers: 'Pilotes', teams: 'Équipes', total: 'Classement général', subtitle: 'Classement automatique à partir des résultats publiés.', season: 'Saison', driverCount: 'pilotes', teamCount: 'équipes', position: 'Pos', trend: 'Tendance', driver: 'Pilote', team: 'Équipe de ligue', car: 'Voiture', wins: 'Victoires', podiums: 'Podiums', fastest: 'Meilleurs tours', points: 'Points', more: 'Afficher plus de statistiques', less: 'Afficher uniquement position, pilote et points', loading: 'Chargement du championnat…', error: 'Impossible de charger le championnat. Vérifiez votre connexion et réessayez.', retry: 'Réessayer', noSeason: 'Aucune saison active.', archive: 'Les classements précédents sont dans les archives des saisons.', emptyDrivers: 'Aucune donnée de pilote pour le moment.', emptyTeams: 'Aucune donnée d’équipe pour le moment.', flat: 'Aucun changement', up: 'Position gagnée', down: 'Position perdue', new: 'Nouveau au classement', scroll: 'Tableau du championnat, défilement horizontal', noTeam: 'Sans équipe' },
};
